/* Set Partitioning Problem tests on generated instances with known optima.

   Formulation:
     minimize   sum_j c[j] * x[j]
     subject to sum_{j: i in S[j]} x[j] = 1   for all i (element i in exactly one set)
                x[j] in {0,1}

   Stricter than set covering (= vs >=), tests equality constraints and
   highly degenerate structures (many optimal solutions).

   For each solve the solution is verified for:
     - structural feasibility via Cbc_checkFeasibility
     - objective value matches known optimum within relative tolerance

   Fixtures in fixtures/*.mps.gz (generated by gen_setpartitioning_fixtures.py).
   This problem tests clique cuts and preprocessing on partitioning structures. */

#include "Cbc_C_Interface.h"
#include "mip_diag.h"
#include "test_utils.h"
#include <math.h>
#include <stdio.h>
#include <string.h>

typedef struct {
  const char *name;
  double expected_obj;
  int max_nodes;
  int timeout_sec;  /* Fallback */
} SetPartitioningTestCase;

static const SetPartitioningTestCase setpartitioning_test_cases[] = {
  {"sprt_e10_s20_sd42_uniform", 192.00, 10000, 300},
  {"sprt_e15_s30_sd42_overlapping", 125.00, 10000, 300},
  {"sprt_e30_s60_sd42_uniform", 629.00, 10000, 300},
  {"sprt_e40_s80_sd137_overlapping", 744.00, 10000, 300},
};

static const int NUM_TESTS = sizeof(setpartitioning_test_cases) / sizeof(setpartitioning_test_cases[0]);

static int test_setpartitioning(const char *fixture_dir, const SetPartitioningTestCase *tc,
                                 MipPerfRecord *perf)
{
  char path[512];
  snprintf(path, sizeof(path), "%s/%s.mps.gz", fixture_dir, tc->name);

  printf("  %s (nodes=%d, expected=%.0f)\n", tc->name, tc->max_nodes, tc->expected_obj);

  perf->name = tc->name; perf->pass = 0; perf->is_optimal = 0;
  perf->nodes = 0; perf->wall_time = 0.0; perf->obj = 1e30;

  Cbc_Model *m = Cbc_newModel();
  Cbc_setLogLevel(m, 0);

  if (Cbc_readMps(m, path) != 0) {
    printf("    FAIL: cannot read %s\n", path);
    Cbc_deleteModel(m);
    return 0;
  }

  Cbc_setMaximumNodes(m, tc->max_nodes);
  double t0 = perf_wall_time();
  Cbc_solve(m);
  perf->wall_time  = perf_wall_time() - t0;
  perf->is_optimal = Cbc_isProvenOptimal(m);
  perf->nodes      = Cbc_getNodeCount(m);

  int pass = 1;
  int nSol = Cbc_numberSavedSolutions(m);

  if (nSol == 0) {
    printf("    FAIL: no feasible solution found (status=%d)\n", Cbc_status(m));
    Cbc_deleteModel(m);
    return 0;
  }

  double obj = Cbc_getObjValue(m);
  perf->obj = obj;

  /* Check feasibility of best and all pool solutions */
  const double *bestSol = Cbc_getColSolution(m);
  double maxViolRow = 0.0; int rowIdx = -1;
  double maxViolCol = 0.0; int colIdx = -1;

  if (!Cbc_checkFeasibility(m, bestSol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
    printf("    FAIL: best solution infeasible  "
           "maxViolRow=%.2e (row %d)  maxViolCol=%.2e (col %d)\n",
           maxViolRow, rowIdx, maxViolCol, colIdx);
    pass = 0;
  }

  for (int s = 0; s < nSol; s++) {
    const double *sol = Cbc_savedSolution(m, s);
    double solObj = Cbc_savedSolutionObj(m, s);
    maxViolRow = 0.0; rowIdx = -1; maxViolCol = 0.0; colIdx = -1;
    if (!Cbc_checkFeasibility(m, sol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
      printf("    FAIL: pool solution %d/%d infeasible (obj=%.2f)  "
             "maxViolRow=%.2e (row %d)  maxViolCol=%.2e (col %d)\n",
             s+1, nSol, solObj, maxViolRow, rowIdx, maxViolCol, colIdx);
      pass = 0;
    }
  }

  /* Only validate objective if solver claims optimality */
  if (perf->is_optimal) {
    double rel_err = fabs(obj - tc->expected_obj) / fmax(fabs(tc->expected_obj), 1.0);
    if (rel_err > 1e-3) {
      printf("    FAIL: proven optimal but obj=%.2f expected=%.2f (rel_err=%.2e)\n",
             obj, tc->expected_obj, rel_err);
      pass = 0;
      char tmp_sol[512];
      snprintf(tmp_sol, sizeof(tmp_sol), "/tmp/mipster_diag_%s.sol", tc->name);
      mip_diag_write_sol(m, tmp_sol);
      mip_diag_wrong_optimal(build_mps_model, (void *)path, tc->expected_obj, 300);
      mip_diag_debug_cuts(build_mps_model, (void *)path, tc->expected_obj, 300,
                          tmp_sol, NULL, NULL);
    }
  }

  if (pass) {
    if (perf->is_optimal)
      printf("    PASS obj=%.0f  nodes=%ld  time=%.3fs  (proven optimal)\n",
             obj, perf->nodes, perf->wall_time);
    else
      printf("    PASS obj=%.0f  nodes=%ld  time=%.3fs  (feasible, not proven optimal)\n",
             obj, perf->nodes, perf->wall_time);
  }

  Cbc_deleteModel(m);
  perf->pass = pass;
  return pass;
}

int main(int argc, char **argv)
{
  if (argc < 2) {
    fprintf(stderr, "Usage: %s <fixture-dir>\n", argv[0]);
    return 1;
  }

  const char *fixture_dir = argv[1];

  printf("=== Set Partitioning Tests ===\n");
  int passed = 0, failed = 0;
  MipPerfRecord perf_records[NUM_TESTS];

  for (int i = 0; i < NUM_TESTS; i++) {
    if (test_setpartitioning(fixture_dir, &setpartitioning_test_cases[i], &perf_records[i]))
      passed++;
    else
      failed++;
  }

  print_perf_summary(perf_records, NUM_TESTS, "Set Partitioning");
  printf("\n");
  if (failed == 0)
    printf("=== All %d tests PASSED ===\n", passed);
  else
    printf("=== %d passed, %d FAILED ===\n", passed, failed);

  return (failed == 0) ? 0 : 1;
}

