/* Maximum (Weighted) Independent Set (MIS/MWIS) tests on generated instances.

   Formulation (maximization):
     maximize   sum_v w[v] * x[v]
     subject to x[u] + x[v] <= 1   for all edges (u,v) in E
                x[v] in {0,1}

   This is the canonical pure binary problem for clique cuts:
     - Independent set in G = clique in complement graph
     - Conflict graph IS the problem structure
     - Tests CglBKClique, CglOddWheel, CglCliqueStrengthening

   For each solve the solution is verified for:
     - structural feasibility via Cbc_checkFeasibility
     - objective value matches known optimum within relative tolerance

   Fixtures in fixtures/*.mps.gz (generated by gen_mis_fixtures.py).
   Includes diverse graph types: random, geometric, grid, tree, planar, etc. */

#include "Cbc_C_Interface.h"
#include <math.h>
#include <stdio.h>
#include <string.h>

typedef struct {
  const char *name;
  double expected_obj;
  int timeout_sec;
} MisTestCase;

static const MisTestCase mis_test_cases[] = {
  {"mis_n15_sd42_random_uniform", 361.00, 10},
  {"mis_n20_sd42_geometric_unit", 6.00, 15},
  {"mis_n16_sd137_grid_diverse", 586.00, 10},
  {"mis_n18_sd42_k_partite_uniform", 338.00, 20},
  {"mis_n20_sd137_tree_uniform", 626.00, 5},
  {"mis_n30_sd42_random_uniform", 490.00, 60},
  {"mis_n35_sd137_geometric_diverse", 709.00, 60},
  {"mis_n36_sd42_grid_unit", 18.00, 30},
  {"mis_n40_sd137_planar_uniform", 1042.00, 90},
  {"mis_n30_sd42_cycle_uniform", 916.00, 10},
};

static const int NUM_TESTS = sizeof(mis_test_cases) / sizeof(mis_test_cases[0]);

static int test_mis(const char *fixture_dir, const MisTestCase *tc)
{
  char path[512];
  snprintf(path, sizeof(path), "%s/%s.mps.gz", fixture_dir, tc->name);

  printf("  %s (timeout=%ds, expected=%.0f)\n", tc->name, tc->timeout_sec, tc->expected_obj);

  Cbc_Model *m = Cbc_newModel();
  Cbc_setLogLevel(m, 0);

  if (Cbc_readMps(m, path) != 0) {
    printf("    FAIL: cannot read %s\n", path);
    Cbc_deleteModel(m);
    return 0;
  }

  Cbc_setMaximumSeconds(m, tc->timeout_sec);
  Cbc_solve(m);

  int pass = 1;

  if (!Cbc_isProvenOptimal(m)) {
    printf("    FAIL: not proven optimal (status=%d, sols=%d)\n",
           Cbc_status(m), Cbc_numberSavedSolutions(m));
    pass = 0;
  }

  const double *sol = Cbc_getColSolution(m);
  double maxViolRow = 0.0; int rowIdx = -1;
  double maxViolCol = 0.0; int colIdx = -1;

  if (!Cbc_checkFeasibility(m, sol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
    printf("    FAIL: Cbc_checkFeasibility failed  "
           "maxViolRow=%.2e (row %d)  maxViolCol=%.2e (col %d)\n",
           maxViolRow, rowIdx, maxViolCol, colIdx);
    pass = 0;
  }

  double obj = Cbc_getObjValue(m);
  /* Note: MPS file has negated objective for maximization */
  obj = -obj;
  double rel_err = fabs(obj - tc->expected_obj) / fmax(fabs(tc->expected_obj), 1.0);

  if (rel_err > 1e-3) {
    printf("    FAIL: obj=%.2f expected=%.2f (rel_err=%.2e)\n",
           obj, tc->expected_obj, rel_err);
    pass = 0;

  }

  if (pass) {
    printf("    PASS obj=%.0f\n", obj);
  }

  Cbc_deleteModel(m);
  return pass;
}

int main(int argc, char **argv)
{
  if (argc < 2) {
    fprintf(stderr, "Usage: %s <fixture-dir>\n", argv[0]);
    return 1;
  }

  const char *fixture_dir = argv[1];

  printf("=== Maximum Independent Set Tests ===\n");
  int passed = 0, failed = 0;

  for (int i = 0; i < NUM_TESTS; i++) {
    if (test_mis(fixture_dir, &mis_test_cases[i])) {
      passed++;
    } else {
      failed++;
    }
  }

  printf("\n");
  if (failed == 0) {
    printf("=== All %d tests PASSED ===\n", passed);
  } else {
    printf("=== %d passed, %d FAILED ===\n", passed, failed);
  }

  return (failed == 0) ? 0 : 1;
}
