/* Steiner Tree Problem tests on generated instances with known optima.

   Formulation (Directed Single-Commodity Flow):
     minimize   sum_{e in E} cost[e] * x[e]
     subject to sum_j f[i,j] - sum_j f[j,i] = supply[i]  for all i (flow conservation)
                f[i,j] + f[j,i] <= capacity * x[e]       for all edges e=(i,j) (capacity link)
                x[e] in {0,1}, f[i,j] >= 0

   where supply[i] = |T| for root, -1 for each terminal, 0 otherwise.

   Tests network flow formulation with:
     - Flow conservation constraints
     - Capacity linking (flow -> edge selection)
     - Mixed binary (edges) and continuous (flow) variables
     - Tree connectivity via single-commodity flow

   For each solve the solution is verified for:
     - structural feasibility via Cbc_checkFeasibility
     - objective value matches known optimum within tolerance

   Fixtures in fixtures/*.mps.gz (generated by gen_steiner_fixtures.py).
   Includes diverse graph types: grid, geometric, complete, sparse. */

#include "Cbc_C_Interface.h"
#include <math.h>
#include <stdio.h>
#include <string.h>

typedef struct {
  const char *name;
  double expected_obj;
  int timeout_sec;
} SteinerTestCase;

static const SteinerTestCase steiner_test_cases[] = {
  {"steiner_grid4x4_t3_corners", 5.0, 30},
  {"steiner_grid5x5_t4_sparse", 8.0, 60},
  {"steiner_geom15_r30_t3", 140.14, 60},
  {"steiner_geom20_r35_t5", 138.48, 120},
  {"steiner_complete10_unit_t4", 4.0, 30},
  {"steiner_complete12_rand_t3", 15.0, 60},
  {"steiner_sparse20_p03_t4", 14.0, 120},
  {"steiner_sparse25_p025_t6", 45.0, 180},
};

static const int NUM_TESTS = sizeof(steiner_test_cases) / sizeof(steiner_test_cases[0]);

static int test_steiner(const char *fixture_dir, const SteinerTestCase *tc)
{
  char path[512];
  snprintf(path, sizeof(path), "%s/%s.mps.gz", fixture_dir, tc->name);

  printf("  %s (timeout=%ds, expected=%.2f)\n", tc->name, tc->timeout_sec, tc->expected_obj);

  Cbc_Model *m = Cbc_newModel();
  Cbc_setLogLevel(m, 0);

  if (Cbc_readMps(m, path) != 0) {
    printf("    FAIL: cannot read %s\n", path);
    Cbc_deleteModel(m);
    return 0;
  }

  Cbc_setMaximumSeconds(m, tc->timeout_sec);
  Cbc_solve(m);

  int pass = 1;

  if (!Cbc_isProvenOptimal(m)) {
    printf("    FAIL: not proven optimal (status=%d, sols=%d)\n",
           Cbc_status(m), Cbc_numberSavedSolutions(m));
    pass = 0;
  }

  /* Check feasibility of best solution */
  const double *bestSol = Cbc_getColSolution(m);
  double maxViolRow = 0.0; int rowIdx = -1;
  double maxViolCol = 0.0; int colIdx = -1;

  if (!Cbc_checkFeasibility(m, bestSol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
    printf("    FAIL: best solution infeasible  "
           "maxViolRow=%.2e (row %d)  maxViolCol=%.2e (col %d)\n",
           maxViolRow, rowIdx, maxViolCol, colIdx);
    pass = 0;
  }

  /* Check feasibility of ALL solutions in the pool */
  int nSol = Cbc_numberSavedSolutions(m);
  for (int s = 0; s < nSol; s++) {
    const double *sol = Cbc_savedSolution(m, s);
    double solObj = Cbc_savedSolutionObj(m, s);
    maxViolRow = 0.0; rowIdx = -1;
    maxViolCol = 0.0; colIdx = -1;

    if (!Cbc_checkFeasibility(m, sol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
      printf("    FAIL: pool solution %d/%d infeasible (obj=%.2f)  "
             "maxViolRow=%.2e (row %d)  maxViolCol=%.2e (col %d)\n",
             s+1, nSol, solObj, maxViolRow, rowIdx, maxViolCol, colIdx);
      pass = 0;
    }
  }

  double obj = Cbc_getObjValue(m);
  double abs_err = fabs(obj - tc->expected_obj);
  double rel_err = abs_err / fmax(fabs(tc->expected_obj), 1.0);

  if (rel_err > 1e-3) {
    printf("    FAIL: obj=%.2f expected=%.2f (rel_err=%.2e)\n",
           obj, tc->expected_obj, rel_err);
    pass = 0;
  }

  if (pass) {
    printf("    PASS obj=%.2f\n", obj);
  }

  Cbc_deleteModel(m);
  return pass;
}

int main(int argc, char **argv)
{
  if (argc < 2) {
    fprintf(stderr, "Usage: %s <fixture-dir>\n", argv[0]);
    return 1;
  }

  const char *fixture_dir = argv[1];

  printf("=== Steiner Tree Tests ===\n");
  int passed = 0, failed = 0;

  for (int i = 0; i < NUM_TESTS; i++) {
    if (test_steiner(fixture_dir, &steiner_test_cases[i])) {
      passed++;
    } else {
      failed++;
    }
  }

  printf("\n");
  if (failed == 0) {
    printf("=== All %d tests PASSED ===\n", passed);
  } else {
    printf("=== %d passed, %d FAILED ===\n", passed, failed);
  }

  return (failed == 0) ? 0 : 1;
}
