/* Set Covering Problem (SCP) tests on generated instances with known optima.

   Formulation:
     minimize   sum_j c[j] * x[j]
     subject to sum_{j: i in S[j]} x[j] >= 1   for all i (element i covered)
                x[j] in {0,1}

   For each solve the solution is verified for:
     - structural feasibility via Cbc_checkFeasibility
     - objective value matches known optimum within relative tolerance
     - solution is truly feasible (all elements covered)

   Fixtures in fixtures/*.mps.gz (generated by gen_setcover_fixtures.py).
   This problem tests clique cut generation on covering structures. */

#include "Cbc_C_Interface.h"
#include "mip_diag.h"
#include <math.h>
#include <stdio.h>
#include <string.h>

typedef struct {
  const char *name;
  double expected_obj;
  int timeout_sec;
} SetCoverTestCase;

static const SetCoverTestCase setcover_test_cases[] = {
  {"scp_e10_s15_sd42_uniform", 59.00, 10},
  {"scp_e15_s20_sd42_sparse", 117.00, 15},
  {"scp_e20_s30_sd42_dense", 13.00, 20},
  {"scp_e20_s25_sd137_hierarchical", 86.00, 20},
  {"scp_e30_s50_sd42_uniform", 41.00, 60},
  {"scp_e40_s60_sd137_sparse", 117.00, 60},
  {"scp_e50_s80_sd42_dense", 11.00, 90},
};

static const int NUM_TESTS = sizeof(setcover_test_cases) / sizeof(setcover_test_cases[0]);

/* Test one set covering instance */
static int test_setcover(const char *fixture_dir, const SetCoverTestCase *tc)
{
  char path[512];
  snprintf(path, sizeof(path), "%s/%s.mps.gz", fixture_dir, tc->name);

  printf("  %s (timeout=%ds, expected=%.0f)\n", tc->name, tc->timeout_sec, tc->expected_obj);

  Cbc_Model *m = Cbc_newModel();
  Cbc_setLogLevel(m, 0);

  if (Cbc_readMps(m, path) != 0) {
    printf("    FAIL: cannot read %s\n", path);
    Cbc_deleteModel(m);
    return 0;
  }

  Cbc_setMaximumSeconds(m, tc->timeout_sec);
  Cbc_solve(m);

  int pass = 1;

  /* Check optimality */
  if (!Cbc_isProvenOptimal(m)) {
    printf("    FAIL: not proven optimal (status=%d)\n", Cbc_status(m));
    pass = 0;
  }

  /* Structural feasibility check */
  /* Check feasibility of best solution */
  const double *bestSol = Cbc_getColSolution(m);
  double maxViolRow = 0.0; int rowIdx = -1;
  double maxViolCol = 0.0; int colIdx = -1;

  if (!Cbc_checkFeasibility(m, bestSol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
    printf("    FAIL: best solution infeasible  "
           "maxViolRow=%.2e (row %d)  maxViolCol=%.2e (col %d)\n",
           maxViolRow, rowIdx, maxViolCol, colIdx);
    pass = 0;
  }

  /* Check feasibility of ALL solutions in the pool */
  int nSol = Cbc_numberSavedSolutions(m);
  for (int s = 0; s < nSol; s++) {
    const double *sol = Cbc_savedSolution(m, s);
    double solObj = Cbc_savedSolutionObjective(m, s);
    maxViolRow = 0.0; rowIdx = -1;
    maxViolCol = 0.0; colIdx = -1;

    if (!Cbc_checkFeasibility(m, sol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
      printf("    FAIL: pool solution %d/%d infeasible (obj=%.2f)  "
             "maxViolRow=%.2e (row %d)  maxViolCol=%.2e (col %d)\n",
             s+1, nSol, solObj, maxViolRow, rowIdx, maxViolCol, colIdx);
      pass = 0;
    }
  }

  double obj = Cbc_getObjValue(m);
  double rel_err = fabs(obj - tc->expected_obj) / fmax(fabs(tc->expected_obj), 1.0);

  if (rel_err > 1e-3) {
    printf("    FAIL: obj=%.2f expected=%.2f (rel_err=%.2e)\n",
           obj, tc->expected_obj, rel_err);
    pass = 0;
  }

  if (pass) {
    printf("    PASS obj=%.0f\n", obj);
  }

  Cbc_deleteModel(m);
  return pass;
}

int main(int argc, char **argv)
{
  if (argc < 2) {
    fprintf(stderr, "Usage: %s <fixture-dir>\n", argv[0]);
    return 1;
  }

  const char *fixture_dir = argv[1];

  printf("=== Set Covering Tests ===\n");
  int passed = 0, failed = 0;

  for (int i = 0; i < NUM_TESTS; i++) {
    if (test_setcover(fixture_dir, &setcover_test_cases[i])) {
      passed++;
    } else {
      failed++;
    }
  }

  printf("\n");
  if (failed == 0) {
    printf("=== All %d tests PASSED ===\n", passed);
  } else {
    printf("=== %d passed, %d FAILED ===\n", passed, failed);
  }

  return (failed == 0) ? 0 : 1;
}
