/* Facility Location tests on randomly generated instances with known optima.
   Two problem classes, two formulations each:

   UFL (Uncapacitated Facility Location):
     1. Individual linking  : x(i,j) <= y(i) for each (i,j)
     2. Aggregated linking  : sum_j x(i,j) <= n * y(i) for each i
        (weaker LP relaxation but same MIP optimum)

   CFLP (Capacitated Facility Location, single-source):
     1. Standard            : x(i,j) <= y(i)  +  sum_j d(j)*x(i,j) <= Q(i)*y(i)
     2. Capacity-only       : sum_j d(j)*x(i,j) <= Q(i)*y(i)
        (individual links omitted — capacity makes them redundant for MIP)

   For each solve the solution is verified for feasibility:
     - every customer is assigned to exactly one open facility
     - CFLP: no facility exceeds its capacity

   Fixture data in fl_fixtures.h (generated by gen_fl_fixtures.py).
   No external files or data packages required. */

#include "Cbc_C_Interface.h"
#include <assert.h>
#include <math.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "fl_fixtures.h"

#define MAX_M 20
#define MAX_N 35

/* ── helpers ──────────────────────────────────────────────────────────────── */

static Cbc_Model *new_model(void)
{
  Cbc_Model *m = Cbc_newModel();
  Cbc_setObjSense(m, 1.0);   /* minimise */
  Cbc_setLogLevel(m, 0);
  return m;
}

/* Add a row with sense 'E'/'L'/'G' */
static void add_row(Cbc_Model *m, int nz, int *idx, double *coef,
                    char sense, double rhs, const char *name)
{
  Cbc_addRow(m, name, nz, idx, coef, sense, rhs);
}

/* Verify solution feasibility and check objective; returns 1 on pass. */
static int check_ufl_solution(Cbc_Model *m, const UflInstance *inst,
                               const char *label)
{
  if (!Cbc_isProvenOptimal(m)) {
    printf("    FAIL [%s]: solver did not prove optimality\n", label);
    return 0;
  }

  /* Structural check: row feasibility, column bounds, integrality (uses solver tolerances) */
  const double *sol = Cbc_getColSolution(m);
  double maxViolRow, maxViolCol;
  int rowIdx, colIdx;
  if (!Cbc_checkFeasibility(m, sol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
    printf("    FAIL [%s]: Cbc_checkFeasibility failed — "
           "maxRowViol=%.2e (row %d)  maxColViol=%.2e (col %d)\n",
           label, maxViolRow, rowIdx, maxViolCol, colIdx);
    return 0;
  }

  int mm = inst->m, n = inst->n;
  int ncols = Cbc_getNumCols(m);

  /* Semantic check: parse solution by name, verify each customer
     is assigned to exactly one open facility */
  double y[MAX_M] = {0}, x[MAX_M][MAX_N] = {{0}};
  for (int k = 0; k < ncols; k++) {
    char name[32]; Cbc_getColName(m, k, name, sizeof(name));
    int a, b;
    if (sscanf(name, "y(%d)", &a) == 1 && a < mm)
      y[a] = sol[k];
    else if (sscanf(name, "x(%d,%d)", &a, &b) == 2 && a < mm && b < n)
      x[a][b] = sol[k];
  }

  for (int j = 0; j < n; j++) {
    double served = 0;
    for (int i = 0; i < mm; i++) {
      if (x[i][j] > 0.5 && y[i] < 0.5) {
        printf("    FAIL [%s]: customer %d assigned to closed facility %d\n",
               label, j, i);
        return 0;
      }
      served += x[i][j];
    }
    if (fabs(served - 1.0) > 1e-4) {
      printf("    FAIL [%s]: customer %d coverage = %.4f\n", label, j, served);
      return 0;
    }
  }

  double obj = Cbc_getObjValue(m);
  if (fabs(obj - inst->opt) > 0.5) {
    printf("    FAIL [%s]: obj=%.1f expected=%d\n", label, obj, inst->opt);
    return 0;
  }
  return 1;
}

static int check_cflp_solution(Cbc_Model *m, const CflpInstance *inst,
                                const char *label)
{
  if (!Cbc_isProvenOptimal(m)) {
    printf("    FAIL [%s]: solver did not prove optimality\n", label);
    return 0;
  }

  const double *sol = Cbc_getColSolution(m);
  double maxViolRow, maxViolCol;
  int rowIdx, colIdx;
  if (!Cbc_checkFeasibility(m, sol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
    printf("    FAIL [%s]: Cbc_checkFeasibility failed — "
           "maxRowViol=%.2e (row %d)  maxColViol=%.2e (col %d)\n",
           label, maxViolRow, rowIdx, maxViolCol, colIdx);
    return 0;
  }

  int mm = inst->m, n = inst->n;
  int ncols = Cbc_getNumCols(m);

  /* Parse solution by name into y[i] and x[i][j] */
  double y[MAX_M] = {0}, x[MAX_M][MAX_N] = {{0}};
  for (int k = 0; k < ncols; k++) {
    char name[32]; Cbc_getColName(m, k, name, sizeof(name));
    int a, b;
    if (sscanf(name, "y(%d)", &a) == 1 && a < mm)
      y[a] = sol[k];
    else if (sscanf(name, "x(%d,%d)", &a, &b) == 2 && a < mm && b < n)
      x[a][b] = sol[k];
  }

  for (int j = 0; j < n; j++) {
    double served = 0;
    for (int i = 0; i < mm; i++) {
      if (x[i][j] > 0.5 && y[i] < 0.5) {
        printf("    FAIL [%s]: customer %d assigned to closed facility %d\n",
               label, j, i);
        return 0;
      }
      served += x[i][j];
    }
    if (fabs(served - 1.0) > 1e-4) {
      printf("    FAIL [%s]: customer %d coverage = %.4f\n", label, j, served);
      return 0;
    }
  }

  /* Capacity check */
  for (int i = 0; i < mm; i++) {
    if (y[i] < 0.5) continue;
    int load = 0;
    for (int j = 0; j < n; j++)
      if (x[i][j] > 0.5) load += inst->dem[j];
    if (load > inst->cap[i]) {
      printf("    FAIL [%s]: facility %d overloaded (load=%d cap=%d)\n",
             label, i, load, inst->cap[i]);
      return 0;
    }
  }

  double obj = Cbc_getObjValue(m);
  if (fabs(obj - inst->opt) > 0.5) {
    printf("    FAIL [%s]: obj=%.1f expected=%d\n", label, obj, inst->opt);
    return 0;
  }
  return 1;
}

/* ── UFL: individual linking x(i,j) <= y(i) ──────────────────────────────── */

static int test_ufl_individual(const UflInstance *inst)
{
  int mm = inst->m, n = inst->n;
  printf("  UFL-individual m=%d n=%d expected=%d\n", mm, n, inst->opt);

  Cbc_Model *m = new_model();

  /* y(i): binary, cost f[i] */
  int ycol[MAX_M];
  for (int i = 0; i < mm; i++) {
    char name[24]; snprintf(name, sizeof(name), "y(%d)", i);
    Cbc_addCol(m, name, 0.0, 1.0, (double)inst->f[i], 1, 0, NULL, NULL);
    ycol[i] = i;
  }

  /* x(i,j): binary, cost c[i*n+j] */
  int xcol[MAX_M][MAX_N];
  int col = mm;
  for (int i = 0; i < mm; i++)
    for (int j = 0; j < n; j++) {
      char name[32]; snprintf(name, sizeof(name), "x(%d,%d)", i, j);
      Cbc_addCol(m, name, 0.0, 1.0, (double)inst->c[i * n + j], 1, 0, NULL, NULL);
      xcol[i][j] = col++;
    }

  /* sum_i x(i,j) = 1  for each customer j */
  for (int j = 0; j < n; j++) {
    int idx[MAX_M]; double coef[MAX_M];
    for (int i = 0; i < mm; i++) { idx[i] = xcol[i][j]; coef[i] = 1.0; }
    char name[32]; snprintf(name, sizeof(name), "serve(%d)", j);
    add_row(m, mm, idx, coef, 'E', 1.0, name);
  }

  /* x(i,j) <= y(i) for each (i,j) */
  for (int i = 0; i < mm; i++)
    for (int j = 0; j < n; j++) {
      int idx[2] = { xcol[i][j], ycol[i] };
      double coef[2] = { 1.0, -1.0 };
      char name[32]; snprintf(name, sizeof(name), "link(%d,%d)", i, j);
      add_row(m, 2, idx, coef, 'L', 0.0, name);
    }

  Cbc_solve(m);
  int ok = check_ufl_solution(m, inst, "UFL-individual");
  printf("    -> obj=%.0f %s\n", Cbc_getObjValue(m), ok ? "OK" : "FAIL");
  Cbc_deleteModel(m);
  return ok;
}

/* ── UFL: aggregated linking sum_j x(i,j) <= n * y(i) ────────────────────── */

static int test_ufl_aggregated(const UflInstance *inst)
{
  int mm = inst->m, n = inst->n;
  printf("  UFL-aggregated m=%d n=%d expected=%d\n", mm, n, inst->opt);

  Cbc_Model *m = new_model();

  int ycol[MAX_M];
  for (int i = 0; i < mm; i++) {
    char name[24]; snprintf(name, sizeof(name), "y(%d)", i);
    Cbc_addCol(m, name, 0.0, 1.0, (double)inst->f[i], 1, 0, NULL, NULL);
    ycol[i] = i;
  }

  int xcol[MAX_M][MAX_N];
  int col = mm;
  for (int i = 0; i < mm; i++)
    for (int j = 0; j < n; j++) {
      char name[32]; snprintf(name, sizeof(name), "x(%d,%d)", i, j);
      Cbc_addCol(m, name, 0.0, 1.0, (double)inst->c[i * n + j], 1, 0, NULL, NULL);
      xcol[i][j] = col++;
    }

  for (int j = 0; j < n; j++) {
    int idx[MAX_M]; double coef[MAX_M];
    for (int i = 0; i < mm; i++) { idx[i] = xcol[i][j]; coef[i] = 1.0; }
    char name[32]; snprintf(name, sizeof(name), "serve(%d)", j);
    add_row(m, mm, idx, coef, 'E', 1.0, name);
  }

  /* sum_j x(i,j) - n * y(i) <= 0 */
  for (int i = 0; i < mm; i++) {
    int idx[MAX_N + 1]; double coef[MAX_N + 1]; int nz = 0;
    for (int j = 0; j < n; j++) { idx[nz] = xcol[i][j]; coef[nz++] = 1.0; }
    idx[nz] = ycol[i]; coef[nz++] = -(double)n;
    char name[32]; snprintf(name, sizeof(name), "agg(%d)", i);
    add_row(m, nz, idx, coef, 'L', 0.0, name);
  }

  Cbc_solve(m);
  int ok = check_ufl_solution(m, inst, "UFL-aggregated");
  printf("    -> obj=%.0f %s\n", Cbc_getObjValue(m), ok ? "OK" : "FAIL");
  Cbc_deleteModel(m);
  return ok;
}

/* ── CFLP: standard (individual links + capacity) ─────────────────────────── */

static int test_cflp_standard(const CflpInstance *inst)
{
  int mm = inst->m, n = inst->n;
  printf("  CFLP-standard m=%d n=%d expected=%d\n", mm, n, inst->opt);

  Cbc_Model *m = new_model();

  int ycol[MAX_M];
  for (int i = 0; i < mm; i++) {
    char name[24]; snprintf(name, sizeof(name), "y(%d)", i);
    Cbc_addCol(m, name, 0.0, 1.0, (double)inst->f[i], 1, 0, NULL, NULL);
    ycol[i] = i;
  }

  int xcol[MAX_M][MAX_N];
  int col = mm;
  for (int i = 0; i < mm; i++)
    for (int j = 0; j < n; j++) {
      char name[32]; snprintf(name, sizeof(name), "x(%d,%d)", i, j);
      Cbc_addCol(m, name, 0.0, 1.0, (double)inst->c[i * n + j], 1, 0, NULL, NULL);
      xcol[i][j] = col++;
    }

  /* Each customer served once */
  for (int j = 0; j < n; j++) {
    int idx[MAX_M]; double coef[MAX_M];
    for (int i = 0; i < mm; i++) { idx[i] = xcol[i][j]; coef[i] = 1.0; }
    char name[32]; snprintf(name, sizeof(name), "serve(%d)", j);
    add_row(m, mm, idx, coef, 'E', 1.0, name);
  }

  /* Individual links x(i,j) <= y(i) */
  for (int i = 0; i < mm; i++)
    for (int j = 0; j < n; j++) {
      int idx[2] = { xcol[i][j], ycol[i] };
      double coef[2] = { 1.0, -1.0 };
      char name[32]; snprintf(name, sizeof(name), "link(%d,%d)", i, j);
      add_row(m, 2, idx, coef, 'L', 0.0, name);
    }

  /* Capacity: sum_j dem[j]*x(i,j) <= cap[i]*y(i) */
  for (int i = 0; i < mm; i++) {
    int idx[MAX_N + 1]; double coef[MAX_N + 1]; int nz = 0;
    for (int j = 0; j < n; j++) { idx[nz] = xcol[i][j]; coef[nz++] = (double)inst->dem[j]; }
    idx[nz] = ycol[i]; coef[nz++] = -(double)inst->cap[i];
    char name[32]; snprintf(name, sizeof(name), "cap(%d)", i);
    add_row(m, nz, idx, coef, 'L', 0.0, name);
  }

  Cbc_solve(m);
  int ok = check_cflp_solution(m, inst, "CFLP-standard");
  printf("    -> obj=%.0f %s\n", Cbc_getObjValue(m), ok ? "OK" : "FAIL");
  Cbc_deleteModel(m);
  return ok;
}

/* ── CFLP: capacity-only (no individual linking constraints) ──────────────── */

static int test_cflp_cap_only(const CflpInstance *inst)
{
  int mm = inst->m, n = inst->n;
  printf("  CFLP-cap-only m=%d n=%d expected=%d\n", mm, n, inst->opt);

  Cbc_Model *m = new_model();

  int ycol[MAX_M];
  for (int i = 0; i < mm; i++) {
    char name[24]; snprintf(name, sizeof(name), "y(%d)", i);
    Cbc_addCol(m, name, 0.0, 1.0, (double)inst->f[i], 1, 0, NULL, NULL);
    ycol[i] = i;
  }

  int xcol[MAX_M][MAX_N];
  int col = mm;
  for (int i = 0; i < mm; i++)
    for (int j = 0; j < n; j++) {
      char name[32]; snprintf(name, sizeof(name), "x(%d,%d)", i, j);
      Cbc_addCol(m, name, 0.0, 1.0, (double)inst->c[i * n + j], 1, 0, NULL, NULL);
      xcol[i][j] = col++;
    }

  for (int j = 0; j < n; j++) {
    int idx[MAX_M]; double coef[MAX_M];
    for (int i = 0; i < mm; i++) { idx[i] = xcol[i][j]; coef[i] = 1.0; }
    char name[32]; snprintf(name, sizeof(name), "serve(%d)", j);
    add_row(m, mm, idx, coef, 'E', 1.0, name);
  }

  /* Capacity only: sum_j dem[j]*x(i,j) <= cap[i]*y(i) */
  for (int i = 0; i < mm; i++) {
    int idx[MAX_N + 1]; double coef[MAX_N + 1]; int nz = 0;
    for (int j = 0; j < n; j++) { idx[nz] = xcol[i][j]; coef[nz++] = (double)inst->dem[j]; }
    idx[nz] = ycol[i]; coef[nz++] = -(double)inst->cap[i];
    char name[32]; snprintf(name, sizeof(name), "cap(%d)", i);
    add_row(m, nz, idx, coef, 'L', 0.0, name);
  }

  Cbc_solve(m);
  int ok = check_cflp_solution(m, inst, "CFLP-cap-only");
  printf("    -> obj=%.0f %s\n", Cbc_getObjValue(m), ok ? "OK" : "FAIL");
  Cbc_deleteModel(m);
  return ok;
}

/* ── main ─────────────────────────────────────────────────────────────────── */

int main(void)
{
  int nfail = 0;

  printf("=== Facility Location Random Instance Tests ===\n");
  printf("    %d UFL + %d CFLP instances, two formulations each\n\n",
         N_UFL_INSTANCES, N_CFLP_INSTANCES);

  for (int k = 0; k < N_UFL_INSTANCES; k++) {
    const UflInstance *inst = &UFL_INSTANCES[k];
    printf("[UFL %d/%d] m=%d n=%d opt=%d\n",
           k + 1, N_UFL_INSTANCES, inst->m, inst->n, inst->opt);
    if (!test_ufl_individual(inst))  nfail++;
    if (!test_ufl_aggregated(inst))  nfail++;
  }

  printf("\n");

  for (int k = 0; k < N_CFLP_INSTANCES; k++) {
    const CflpInstance *inst = &CFLP_INSTANCES[k];
    printf("[CFLP %d/%d] m=%d n=%d opt=%d\n",
           k + 1, N_CFLP_INSTANCES, inst->m, inst->n, inst->opt);
    if (!test_cflp_standard(inst))  nfail++;
    if (!test_cflp_cap_only(inst))  nfail++;
  }

  printf("\n");
  if (nfail == 0)
    printf("=== All facility location tests PASSED ===\n");
  else
    printf("=== FAILED: %d test(s) failed ===\n", nfail);

  return nfail > 0 ? 1 : 0;
}
