/* Generalized Assignment Problem (GAP) tests on generated instances.

   Formulation (minimization):
     minimize   sum_{i,j} c[i][j] * x[i][j]
     subject to sum_i x[i][j] = 1              for all j  (each task assigned once)
                sum_j w[i][j] * x[i][j] <= b[i] for all i  (agent capacity)
                x[i][j] in {0,1}

   where c[i][j] = cost, w[i][j] = resource use, b[i] = agent capacity.

   The suite covers 5 diversity dimensions:
     Cost type:   anticorr (light=expensive, large LP-MIP gap, requires B&B),
                  uniform, structured (agent specialisation)
     Weight type: uniform [1,10], variable [1,20], heavy [5,20]
     Tightness:   tight (alpha~1.08-1.15), medium (alpha~1.5)
     Size:        100-300 binary variables (4-10 agents × 20-40 tasks)
     Seed:        42 or 137

   Anti-correlated instances exercise branching most: the LP can fractionally
   assign cheap (heavy) tasks to all agents, but integrality + capacity make
   that infeasible, forcing genuine branch-and-bound.

   For each solve the solution is verified for:
     - structural feasibility via Cbc_checkFeasibility
     - objective value matches certified optimum (within tolerance)
       when the solver reports isProvenOptimal

   Fixtures in fixtures/*.mps.gz (generated by gen_gap_fixtures.py). */

#include "Cbc_C_Interface.h"
#include "mip_diag.h"
#include "test_utils.h"
#include <math.h>
#include <stdio.h>
#include <string.h>

typedef struct {
  const char *name;
  double      expected_obj;
  int         max_nodes;
  int         timeout_sec;
} GapTestCase;

static const GapTestCase gap_test_cases[] = {
  /* ── Anti-correlated: require genuine branch-and-bound ─────────────────── */
  /* warm-up: ~500 nodes, < 0.3 s */
  {"gap_4a35t_sd42_tight_anticorr_uniform",    1270, 50000, 120},
  /* small-medium: ~1000-6000 nodes, < 0.7 s */
  {"gap_6a30t_sd42_tight_anticorr_uniform",    1003, 50000, 120},
  {"gap_4a35t_sd137_tight_anticorr_uniform",   1252, 50000, 120},
  /* medium: ~5000-12000 nodes, 0.5-1.5 s */
  {"gap_4a40t_sd42_tight_anticorr_variable",   2368, 50000, 120},
  {"gap_6a35t_sd42_tight_anticorr_uniform",    1167, 50000, 120},
  {"gap_5a30t_sd42_tight_anticorr_variable",   1738, 50000, 120},
  /* hard: ~12000-22000 nodes, 2-3 s; heavy weights make packing harder */
  {"gap_6a30t_sd137_tight_anticorr_heavy",     1834, 100000, 300},
  {"gap_5a35t_sd137_tight_anticorr_variable",  1896, 100000, 300},

  /* ── Other cost types: verify correctness (solve at root) ──────────────── */
  {"gap_5a20t_sd42_tight_uniform_uniform",      458,  5000,  60},
  {"gap_5a20t_sd137_tight_structured_uniform",  295,  5000,  60},
  {"gap_10a30t_sd42_medium_uniform_uniform",    313,  5000,  60},
};

static const int NUM_TESTS = sizeof(gap_test_cases) / sizeof(gap_test_cases[0]);

static int test_gap(const char *fixture_dir, const GapTestCase *tc,
                    MipPerfRecord *perf)
{
  char path[512];
  snprintf(path, sizeof(path), "%s/%s.mps.gz", fixture_dir, tc->name);

  printf("  %s (nodes=%d, expected=%.0f)\n",
         tc->name, tc->max_nodes, tc->expected_obj);

  perf->name       = tc->name;
  perf->pass       = 0;
  perf->is_optimal = 0;
  perf->nodes      = 0;
  perf->wall_time  = 0.0;
  perf->obj        = 1e30;

  Cbc_Model *m = Cbc_newModel();
  Cbc_setLogLevel(m, 0);

  if (Cbc_readMps(m, path) != 0) {
    printf("    FAIL: cannot read %s\n", path);
    Cbc_deleteModel(m);
    return 0;
  }

  Cbc_setMaximumNodes(m, tc->max_nodes);
  Cbc_setMaximumSeconds(m, tc->timeout_sec);

  double t0 = perf_wall_time();
  Cbc_solve(m);
  perf->wall_time  = perf_wall_time() - t0;
  perf->is_optimal = Cbc_isProvenOptimal(m);
  perf->nodes      = Cbc_getNodeCount(m);

  int pass = 1;
  int nSol = Cbc_numberSavedSolutions(m);

  if (nSol == 0) {
    printf("    FAIL: no feasible solution found (status=%d)\n", Cbc_status(m));
    Cbc_deleteModel(m);
    return 0;
  }

  double obj = Cbc_getObjValue(m);
  perf->obj = obj;

  /* Feasibility check — best solution */
  const double *bestSol = Cbc_getColSolution(m);
  double maxViolRow = 0.0;
  int    rowIdx     = -1;
  double maxViolCol = 0.0;
  int    colIdx     = -1;
  if (!Cbc_checkFeasibility(m, bestSol, &maxViolRow, &rowIdx,
                                        &maxViolCol, &colIdx)) {
    printf("    FAIL: best solution infeasible  "
           "maxViolRow=%.2e (row %d)  maxViolCol=%.2e (col %d)\n",
           maxViolRow, rowIdx, maxViolCol, colIdx);
    pass = 0;
  }

  /* Feasibility check — entire solution pool */
  for (int s = 0; s < nSol; s++) {
    const double *sol    = Cbc_savedSolution(m, s);
    double        solObj = Cbc_savedSolutionObj(m, s);
    maxViolRow = 0.0; rowIdx = -1;
    maxViolCol = 0.0; colIdx = -1;
    if (!Cbc_checkFeasibility(m, sol, &maxViolRow, &rowIdx,
                                      &maxViolCol, &colIdx)) {
      printf("    FAIL: pool solution %d/%d infeasible (obj=%.2f)  "
             "maxViolRow=%.2e (row %d)  maxViolCol=%.2e (col %d)\n",
             s + 1, nSol, solObj,
             maxViolRow, rowIdx, maxViolCol, colIdx);
      pass = 0;
    }
  }

  /* Objective check — only when solver claims optimality */
  if (perf->is_optimal) {
    double tol = mip_obj_tol(m, tc->expected_obj, 0.5);
    if (fabs(obj - tc->expected_obj) > tol) {
      printf("    FAIL: proven optimal but obj=%.0f != expected=%.0f (tol=%.1f)\n",
             obj, tc->expected_obj, tol);
      pass = 0;

      char tmp_sol[512];
      snprintf(tmp_sol, sizeof(tmp_sol), "/tmp/mipster_diag_%s.sol", tc->name);
      mip_diag_write_sol(m, tmp_sol);
      mip_diag_wrong_optimal(build_mps_model, (void *)path,
                             tc->expected_obj, 300);
      mip_diag_debug_cuts(build_mps_model, (void *)path,
                          tc->expected_obj, 300, tmp_sol, NULL, NULL);
    }
  }

  if (pass) {
    if (perf->is_optimal)
      printf("    PASS obj=%.0f  nodes=%ld  time=%.3fs  (proven optimal)\n",
             obj, perf->nodes, perf->wall_time);
    else
      printf("    PASS obj=%.0f  nodes=%ld  time=%.3fs  (feasible, not proven optimal)\n",
             obj, perf->nodes, perf->wall_time);
  }

  Cbc_deleteModel(m);
  perf->pass = pass;
  return pass;
}

int main(int argc, char **argv)
{
  if (argc < 2) {
    fprintf(stderr, "Usage: %s <fixture-dir>\n", argv[0]);
    return 1;
  }

  const char *fixture_dir = argv[1];

  printf("=== Generalized Assignment Problem Tests ===\n");
  int passed = 0, failed = 0;
  MipPerfRecord perf_records[NUM_TESTS];

  for (int i = 0; i < NUM_TESTS; i++) {
    if (test_gap(fixture_dir, &gap_test_cases[i], &perf_records[i]))
      passed++;
    else
      failed++;
  }

  print_perf_summary(perf_records, NUM_TESTS, "Generalized Assignment");
  printf("\n");
  if (failed == 0)
    printf("=== All %d tests PASSED ===\n", passed);
  else
    printf("=== %d passed, %d FAILED ===\n", passed, failed);

  return (failed == 0) ? 0 : 1;
}
