/* Job Shop Scheduling Problem (JSSP) tests on classic benchmark instances.

   JSSP formulation (disjunctive/big-M):
     minimize   C (makespan)
     subject to x[j][op] + p[j][op] <= x[j][op+1]           (precedence within job)
                x[j][op_j] + p[j][op_j] <= x[k][op_k] + M*(1 - y[j][k][m])  (disjunctive)
                x[k][op_k] + p[k][op_k] <= x[j][op_j] + M*y[j][k][m]
                x[j][last_op] + p[j][last_op] <= C          (makespan definition)
                x[j][op] >= 0, y[j][k][m] in {0,1}

   Tests big-M disjunctive constraints, sequencing binaries, and time-indexed
   scheduling formulations.

   For each solve the solution is verified for:
     - structural feasibility via Cbc_checkFeasibility
     - objective value (makespan) matches known optimum within tolerance

   Fixtures from classic JSSP benchmarks (Fisher & Thompson, Lawrence,
   Applegate & Cook) in fixtures/*.mps.gz (generated by gen_jssp_fixtures.py).

   Diversity:
     - Size: 6x6 to 20x5
     - Structures: Fisher & Thompson (balanced), Lawrence (rectangular),
       Applegate & Cook (square with diverse processing times)
     - Processing time distributions
     - Machine orderings */

#include "Cbc_C_Interface.h"
#include "mip_diag.h"
#include <math.h>
#include <stdio.h>
#include <string.h>

typedef struct {
  const char *name;
  double expected_makespan;
  int max_nodes;    /* Primary deterministic stop. Keep relaxed. */
  int timeout_sec;  /* Wall-clock fallback (loose) — only triggers under
                       pathological behaviour or sanitizer slowdown. */
} JsspTestCase;

/* Builder for mip_diag_*: load fixture from path. Diag helpers free the model. */
static Cbc_Model *jssp_builder(void *userdata)
{
  const char *path = (const char *)userdata;
  Cbc_Model *m = Cbc_newModel();
  if (Cbc_readMps(m, path) != 0) {
    fprintf(stderr, "  [DIAG] builder: cannot read %s\n", path);
  }
  return m;
}

/* Limits are deliberately loose: node limit is the deterministic stop,
 * time limit is a wall-clock fallback (machine-dependent — tight values
 * cause flaky failures on slow CI runners or sanitizer builds). */
static const JsspTestCase jssp_test_cases[] = {
  {"jssp_ft06",    55,  500000, 300},  /* Fisher & Thompson 6x6 */
  {"jssp_ft10",   930,  500000, 300},  /* Fisher & Thompson 10x10 */
  {"jssp_la01",   666,  500000, 300},  /* Lawrence 10x5 */
  {"jssp_la06",   926,  500000, 300},  /* Lawrence 15x5 */
  {"jssp_la11",  1222,  500000, 300},  /* Lawrence 20x5 */
  {"jssp_orb01", 1059,  500000, 300},  /* Applegate & Cook 10x10 */
};

static const int NUM_TESTS = sizeof(jssp_test_cases) / sizeof(jssp_test_cases[0]);

/* Resolve <fixture_dir>/solutions/<name>.sol if it exists, else NULL.
 * Returns a pointer to the static buffer `out` (caller-supplied). */
static const char *jssp_solution_path(const char *fixture_dir, const char *name,
                                      char *out, size_t out_sz)
{
  snprintf(out, out_sz, "%s/solutions/%s.sol", fixture_dir, name);
  FILE *f = fopen(out, "r");
  if (!f)
    return NULL;
  fclose(f);
  return out;
}

static int test_jssp(const char *fixture_dir, const JsspTestCase *tc)
{
  char path[512];
  snprintf(path, sizeof(path), "%s/%s.mps.gz", fixture_dir, tc->name);

  printf("  %s (timeout=%ds, expected makespan=%.0f)\n",
         tc->name, tc->timeout_sec, tc->expected_makespan);

  Cbc_Model *m = Cbc_newModel();
  Cbc_setLogLevel(m, 0);

  if (Cbc_readMps(m, path) != 0) {
    printf("    FAIL: cannot read %s\n", path);
    Cbc_deleteModel(m);
    return 0;
  }

  Cbc_setMaximumNodes(m, tc->max_nodes);
  Cbc_setMaximumSeconds(m, tc->timeout_sec);  /* wall-clock fallback only */
  Cbc_solve(m);

  int pass = 1;
  int is_proven_optimal = Cbc_isProvenOptimal(m);

  /* Check feasibility of best solution */
  const double *bestSol = Cbc_getColSolution(m);
  double maxViolRow = 0.0; int rowIdx = -1;
  double maxViolCol = 0.0; int colIdx = -1;

  if (!Cbc_checkFeasibility(m, bestSol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
    printf("    FAIL: best solution infeasible  "
           "maxViolRow=%.2e (row %d)  maxViolCol=%.2e (col %d)\n",
           maxViolRow, rowIdx, maxViolCol, colIdx);
    pass = 0;
  }

  /* Check feasibility of ALL solutions in the pool */
  int nSol = Cbc_numberSavedSolutions(m);
  for (int s = 0; s < nSol; s++) {
    const double *sol = Cbc_savedSolution(m, s);
    double solObj = Cbc_savedSolutionObj(m, s);
    maxViolRow = 0.0; rowIdx = -1;
    maxViolCol = 0.0; colIdx = -1;

    if (!Cbc_checkFeasibility(m, sol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
      printf("    FAIL: pool solution %d/%d infeasible (obj=%.0f)  "
             "maxViolRow=%.2e (row %d)  maxViolCol=%.2e (col %d)\n",
             s+1, nSol, solObj, maxViolRow, rowIdx, maxViolCol, colIdx);
      pass = 0;
    }
  }

  /* Check best solution objective */
  double makespan = Cbc_getObjValue(m);
  double abs_err = fabs(makespan - tc->expected_makespan);

  /* Only require correct objective if solver claims optimality */
  if (is_proven_optimal && abs_err > 0.5) {
    printf("    FAIL: proven optimal but makespan=%.0f expected=%.0f (error=%.1f)\n",
           makespan, tc->expected_makespan, abs_err);
    pass = 0;

    printf("    [DIAG] running wrong-optimal feature sweep on %s ...\n", tc->name);
    mip_diag_wrong_optimal(jssp_builder, (void *)path,
                           tc->expected_makespan, tc->timeout_sec);

    /* If a per-fixture reference solution is available, run debugCuts to
     * identify cut generators producing rows that exclude the certified
     * optimum.  Default config catches always-invalid cuts; a second pass
     * with nodeBoundProp=on isolates cuts generated under tightened node
     * bounds. */
    char sol_buf[512];
    const char *sol = jssp_solution_path(fixture_dir, tc->name,
                                         sol_buf, sizeof(sol_buf));
    if (sol) {
      mip_diag_debug_cuts(jssp_builder, (void *)path,
                          tc->expected_makespan, tc->timeout_sec,
                          sol, NULL, NULL);
      mip_diag_debug_cuts(jssp_builder, (void *)path,
                          tc->expected_makespan, tc->timeout_sec,
                          sol, "nodeBoundProp", "on");
    } else {
      printf("    [DIAG] no reference .sol for %s — skipping debugCuts pass\n",
             tc->name);
    }
  }

  if (pass) {
    if (is_proven_optimal) {
      printf("    PASS makespan=%.0f (proven optimal)\n", makespan);
    } else {
      printf("    PASS makespan=%.0f (not proven, status=%d)\n",
             makespan, Cbc_status(m));
    }
  }

  Cbc_deleteModel(m);
  return pass;
}

int main(int argc, char **argv)
{
  if (argc < 2) {
    fprintf(stderr, "Usage: %s <fixture-dir>\n", argv[0]);
    return 1;
  }

  const char *fixture_dir = argv[1];

  printf("=== Job Shop Scheduling Tests ===\n");
  int passed = 0, failed = 0;

  for (int i = 0; i < NUM_TESTS; i++) {
    if (test_jssp(fixture_dir, &jssp_test_cases[i])) {
      passed++;
    } else {
      failed++;
    }
  }

  printf("\n");
  if (failed == 0) {
    printf("=== All %d tests PASSED ===\n", passed);
  } else {
    printf("=== %d passed, %d FAILED ===\n", passed, failed);
  }

  return (failed == 0) ? 0 : 1;
}
