/* Unrelated Parallel Machine Scheduling with Sequence-Dependent Setup Times
   (UPMSP-ST) tests on generated instances with certified optimal values.

   Formulation (big-M, two objective variants):
     Variables:
       Cmax             continuous, objective (makespan variant)
       C[j]             continuous, completion time of job j
       x[j][k]          binary, 1 if job j assigned to machine k
       d[i][j][k]       binary (i<j), 1 if job i precedes job j on machine k

     Constraints for each pair i<j and machine k:
       asgn_j:    sum_k x[j][k] = 1
       lb_j_k:    C[j] - M*x[j][k]                                >= p[j][k] - M
       prA_i_j_k: C[j]-C[i] - M*d[i,j,k] - M*x[i,k] - M*x[j,k] >= p[j,k]+s[i,j,k] - 3M
       prB_i_j_k: C[i]-C[j] + M*d[i,j,k] - M*x[i,k] - M*x[j,k] >= p[i,k]+s[j,i,k] - 2M
       cmax_j:    Cmax - C[j]                                      >= 0 (makespan only)

     Objectives:
       Makespan (Cmax): minimize latest completion time
       WCT:             minimize sum_j w[j]*C[j]  (weighted completion time)

   Six diverse instances (generated by gen_upms_fixtures.py):
     1. n=8, m=2, integer proc/setup, Cmax          opt=55
     2. n=8, m=3, integer proc/setup, WCT           opt=273
     3. n=9, m=3, integer proc/setup, Cmax          opt=57
     4. n=8, m=3, fractional proc/setup (0.5 grid), Cmax  opt=24.5
     5. n=9, m=2, large setup times, Cmax           opt=87
     6. n=7, m=3, integer proc/setup, WCT           opt=202

   All optimal values are independently certified.

   Test policy (node-limited):
     - Node limit is the primary deterministic stop; time limit is a loose fallback.
     - Feasibility of every solution in the pool is ALWAYS verified.
     - Objective is verified ONLY when the solver claims proven optimality; the
       claimed value must match the certified optimum within solver gap tolerances.
     - Not proving optimal within the node budget is acceptable — the test still
       passes as long as every solution produced is feasible.
*/

#include "Cbc_C_Interface.h"
#include "mip_diag.h"
#include "test_utils.h"
#include <math.h>
#include <stdio.h>
#include <string.h>

typedef struct {
  const char *name;
  double      certified_opt; /* independently verified optimal value */
  int         max_nodes;     /* primary deterministic stop */
  int         timeout_sec;   /* wall-clock fallback (loose) */
} UpmsTestCase;

/* Node limits are generous: the point is to exercise branching, not to
   guarantee a proof of optimality.  The time limit is a safety net for
   sanitizer builds or very slow CI runners. */
static const UpmsTestCase upms_test_cases[] = {
  /* name                        cert_opt  nodes   sec */
  {"upms_n8_m2_int_cmax_s42",   55.0,    500000, 300}, /* 8j 2m int  Cmax */
  {"upms_n8_m3_int_wct_s42",   273.0,    500000, 300}, /* 8j 3m int  WCT  */
  {"upms_n9_m3_int_cmax_s137",  57.0,    500000, 300}, /* 9j 3m int  Cmax */
  {"upms_n8_m3_frac_cmax_s42",  24.5,    500000, 300}, /* 8j 3m frac Cmax */
  {"upms_n9_m2_lgset_cmax_s137",87.0,    500000, 300}, /* 9j 2m lgst Cmax */
  {"upms_n7_m3_int_wct_s137",  202.0,    500000, 300}, /* 7j 3m int  WCT  */
};

static const int NUM_TESTS = sizeof(upms_test_cases) / sizeof(upms_test_cases[0]);

/* ── mip_diag builder ──────────────────────────────────────────────────────── */

static Cbc_Model *upms_builder(void *userdata)
{
  const char *path = (const char *)userdata;
  Cbc_Model *m = Cbc_newModel();
  if (Cbc_readMps(m, path) != 0) {
    fprintf(stderr, "  [DIAG] builder: cannot read %s\n", path);
    Cbc_deleteModel(m);
    return NULL;
  }
  return m;
}

/* ── per-instance test ─────────────────────────────────────────────────────── */

static int test_upms(const char *fixture_dir, const UpmsTestCase *tc)
{
  char path[512];
  snprintf(path, sizeof(path), "%s/%s.mps.gz", fixture_dir, tc->name);

  printf("  %s\n", tc->name);
  printf("    certified_opt=%.4g  max_nodes=%d  timeout=%ds\n",
         tc->certified_opt, tc->max_nodes, tc->timeout_sec);

  Cbc_Model *m = Cbc_newModel();
  Cbc_setLogLevel(m, 0);

  if (Cbc_readMps(m, path) != 0) {
    printf("    FAIL: cannot read %s\n", path);
    Cbc_deleteModel(m);
    return 0;
  }

  Cbc_setMaximumNodes(m, tc->max_nodes);
  Cbc_setMaximumSeconds(m, tc->timeout_sec);

  double t0 = perf_wall_time();
  Cbc_solve(m);
  double elapsed = perf_wall_time() - t0;

  int pass          = 1;
  int is_optimal    = Cbc_isProvenOptimal(m);
  int nSol          = Cbc_numberSavedSolutions(m);
  long nodes        = (long)Cbc_getNodeCount(m);
  double obj        = Cbc_getObjValue(m);

  printf("    nodes=%ld  time=%.2fs  is_optimal=%d  obj=%.4g  pool=%d\n",
         nodes, elapsed, is_optimal, obj, nSol);

  /* ── 1. Every solution in the pool must be feasible ─────────────────────── */
  if (nSol == 0) {
    /* Acceptable only if the node budget ran out before any integer solution
       was found.  Treat as a soft warning, not a hard failure. */
    printf("    WARNING: no integer solution found within node limit\n");
  }

  for (int s = 0; s < nSol; s++) {
    const double *sol    = Cbc_savedSolution(m, s);
    double        solObj = Cbc_savedSolutionObj(m, s);
    double maxViolRow = 0.0, maxViolCol = 0.0;
    int    rowIdx = -1,      colIdx = -1;

    if (!Cbc_checkFeasibility(m, sol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
      printf("    FAIL: pool solution %d/%d infeasible (obj=%.4g)  "
             "maxViolRow=%.2e (row %d)  maxViolCol=%.2e (col %d)\n",
             s + 1, nSol, solObj,
             maxViolRow, rowIdx, maxViolCol, colIdx);
      pass = 0;
    }
  }

  /* Also check best solution separately (it may differ from pool[0]) */
  const double *bestSol = Cbc_bestSolution(m);
  if (bestSol) {
    double maxViolRow = 0.0, maxViolCol = 0.0;
    int    rowIdx = -1,      colIdx = -1;
    if (!Cbc_checkFeasibility(m, bestSol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
      printf("    FAIL: best solution infeasible  "
             "maxViolRow=%.2e (row %d)  maxViolCol=%.2e (col %d)\n",
             maxViolRow, rowIdx, maxViolCol, colIdx);
      pass = 0;
    }
  }

  /* ── 2. Objective check — only when solver claims proven optimality ───────
     Uses solver gap tolerances (ratioGap / allowableGap) so the test
     remains correct regardless of solver settings.                          */
  if (is_optimal && nSol > 0) {
    double tol   = mip_obj_tol(m, tc->certified_opt, 1e-4);
    double error = fabs(obj - tc->certified_opt);
    if (error > tol) {
      printf("    FAIL: claims optimal obj=%.6f but certified=%.6f "
             "(error=%.6f > tol=%.6f)\n",
             obj, tc->certified_opt, error, tol);
      pass = 0;

      /* Diagnostic sweep: disable cut families one at a time */
      printf("    [DIAG] running feature sweep …\n");
      mip_diag_wrong_optimal(upms_builder, (void *)path,
                             tc->certified_opt, tc->timeout_sec);

      /* debugCuts pass (no reference solution — uses feasibility oracle) */
      mip_diag_debug_cuts(upms_builder, (void *)path,
                          tc->certified_opt, tc->timeout_sec,
                          NULL, NULL, NULL);
    }
  }

  if (pass) {
    if (is_optimal)
      printf("    PASS (proven optimal obj=%.4g)\n", obj);
    else if (nSol > 0)
      printf("    PASS (feasible obj=%.4g, not proven optimal)\n", obj);
    else
      printf("    PASS (no solution found within node limit)\n");
  }

  Cbc_deleteModel(m);
  return pass;
}

/* ── main ──────────────────────────────────────────────────────────────────── */

int main(int argc, char **argv)
{
  if (argc < 2) {
    fprintf(stderr, "Usage: %s <fixture-dir>\n", argv[0]);
    return 1;
  }
  const char *fixture_dir = argv[1];

  printf("=== UPMSP-ST Tests (Unrelated Parallel Machine Scheduling) ===\n");

  int passed = 0, failed = 0;
  double t_total = perf_wall_time();

  for (int i = 0; i < NUM_TESTS; i++) {
    if (test_upms(fixture_dir, &upms_test_cases[i]))
      passed++;
    else
      failed++;
  }

  double elapsed = perf_wall_time() - t_total;
  printf("\n%d/%d tests passed  (%.1fs total)\n",
         passed, NUM_TESTS, elapsed);
  return (failed == 0) ? 0 : 1;
}
