/* Fixed Charge Network Flow (FCNF) tests on generated instances with
   known optima.

   Formulation:
     minimize   sum_a (cost_a * x_a + fixed_a * y_a)
     subject to flow conservation at every node
                0 <= x_a <= cap_a * y_a    (variable upper bound, links flow to fixed-charge binary)
                y_a in {0,1}, x_a continuous

   Exercises FlowCover, MIR, Gomory and Twomir cut generators on
   structured min-cost-flow-with-fixed-charges instances spanning grids,
   hubs, layered DAGs, complete bipartite, and random networks with
   varied capacity/charge magnitudes.

   For each solve the solution is verified for:
     - structural feasibility via Cbc_checkFeasibility (best + all pool)
     - if proven optimal, objective matches the certified optimum

   Fixtures in fixtures/fcnf_*.mps.gz (generated by gen_fcnf_fixtures.py). */

#include "Cbc_C_Interface.h"
#include <math.h>
#include <stdio.h>
#include <string.h>

typedef struct {
  const char *name;
  double expected_obj;
  int max_nodes;
  int timeout_sec;
} FCNFTestCase;

static const FCNFTestCase fcnf_test_cases[] = {
  {"fcnf_complete_bip_5x5",        201.110000,    50000, 120},
  {"fcnf_grid_4x4_balanced",        74.270000,    50000, 120},
  {"fcnf_grid_4x4_multimagnitude", 198.820000,    50000, 120},
  {"fcnf_grid_5x5_fixedheavy",     286.610000,    50000, 120},
  {"fcnf_hub_n12",                 466.920000,    50000, 120},
  {"fcnf_layered_3stage",          182.448000,    50000, 120},
  {"fcnf_layered_continuous_loose", 2893.838200,  50000, 120},
  {"fcnf_random_n15_d3",            79.880000,    50000, 120},
  {"fcnf_random_n20_d4_tight",     658.590000,    50000, 120},
};

static const int NUM_TESTS = sizeof(fcnf_test_cases) / sizeof(fcnf_test_cases[0]);

static int test_fcnf(const char *fixture_dir, const FCNFTestCase *tc)
{
  char path[512];
  snprintf(path, sizeof(path), "%s/%s.mps.gz", fixture_dir, tc->name);

  printf("  %s (timeout=%ds, expected=%.4f)\n",
         tc->name, tc->timeout_sec, tc->expected_obj);

  Cbc_Model *m = Cbc_newModel();
  Cbc_setLogLevel(m, 0);

  if (Cbc_readMps(m, path) != 0) {
    printf("    FAIL: cannot read %s\n", path);
    Cbc_deleteModel(m);
    return 0;
  }

  Cbc_setMaximumNodes(m, tc->max_nodes);
  Cbc_setMaximumSeconds(m, tc->timeout_sec);
  Cbc_solve(m);

  int pass = 1;
  int is_proven_optimal = Cbc_isProvenOptimal(m);
  int nSol = Cbc_numberSavedSolutions(m);

  if (nSol == 0) {
    printf("    FAIL: no feasible solution found (status=%d)\n", Cbc_status(m));
    Cbc_deleteModel(m);
    return 0;
  }

  const double *bestSol = Cbc_getColSolution(m);
  double maxViolRow = 0.0; int rowIdx = -1;
  double maxViolCol = 0.0; int colIdx = -1;

  if (!Cbc_checkFeasibility(m, bestSol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
    printf("    FAIL: best solution infeasible  "
           "maxViolRow=%.2e (row %d)  maxViolCol=%.2e (col %d)\n",
           maxViolRow, rowIdx, maxViolCol, colIdx);
    pass = 0;
  }

  for (int s = 0; s < nSol; s++) {
    const double *sol = Cbc_savedSolution(m, s);
    double solObj = Cbc_savedSolutionObj(m, s);
    maxViolRow = 0.0; rowIdx = -1;
    maxViolCol = 0.0; colIdx = -1;

    if (!Cbc_checkFeasibility(m, sol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
      printf("    FAIL: pool solution %d/%d infeasible (obj=%.4f)  "
             "maxViolRow=%.2e (row %d)  maxViolCol=%.2e (col %d)\n",
             s+1, nSol, solObj, maxViolRow, rowIdx, maxViolCol, colIdx);
      pass = 0;
    }
  }

  double obj = Cbc_getObjValue(m);
  double rel_err = fabs(obj - tc->expected_obj) / fmax(fabs(tc->expected_obj), 1.0);

  if (is_proven_optimal && rel_err > 1e-3) {
    printf("    FAIL: proven optimal but obj=%.4f expected=%.4f (rel_err=%.2e)\n",
           obj, tc->expected_obj, rel_err);
    pass = 0;
  }

  if (pass) {
    if (is_proven_optimal) {
      printf("    PASS obj=%.4f (proven optimal)\n", obj);
    } else {
      printf("    PASS obj=%.4f (feasible, not proven, status=%d)\n",
             obj, Cbc_status(m));
    }
  }

  Cbc_deleteModel(m);
  return pass;
}

int main(int argc, char **argv)
{
  if (argc < 2) {
    fprintf(stderr, "Usage: %s <fixture-dir>\n", argv[0]);
    return 1;
  }

  const char *fixture_dir = argv[1];

  printf("=== Fixed Charge Network Flow Tests ===\n");
  int passed = 0, failed = 0;

  for (int i = 0; i < NUM_TESTS; i++) {
    if (test_fcnf(fixture_dir, &fcnf_test_cases[i])) {
      passed++;
    } else {
      failed++;
    }
  }

  printf("\n");
  if (failed == 0) {
    printf("=== All %d tests PASSED ===\n", passed);
  } else {
    printf("=== %d passed, %d FAILED ===\n", passed, failed);
  }

  return (failed == 0) ? 0 : 1;
}
