/* Steiner Tree Problem tests on generated instances with known optima.

   Formulation (Directed Single-Commodity Flow):
     minimize   sum_{e in E} cost[e] * x[e]
     subject to sum_j f[i,j] - sum_j f[j,i] = supply[i]  for all i (flow conservation)
                f[i,j] + f[j,i] <= capacity * x[e]       for all edges e=(i,j) (capacity link)
                x[e] in {0,1}, f[i,j] >= 0

   where supply[i] = |T| for root, -1 for each terminal, 0 otherwise.

   Tests network flow formulation with:
     - Flow conservation constraints
     - Capacity linking (flow -> edge selection)
     - Mixed binary (edges) and continuous (flow) variables
     - Tree connectivity via single-commodity flow

   For each solve the solution is verified for:
     - structural feasibility via Cbc_checkFeasibility
     - objective value matches known optimum within tolerance

   Fixtures in fixtures/*.mps.gz (generated by gen_steiner_fixtures.py).
   Includes diverse graph types: grid, geometric, complete, sparse. */

#include "Cbc_C_Interface.h"
#include "mip_diag.h"
#include "test_utils.h"
#include <math.h>
#include <stdio.h>
#include <string.h>

typedef struct {
  const char *name;
  double expected_obj;
  int max_nodes;
  int timeout_sec;  /* Fallback to prevent infinite loops */
} SteinerTestCase;

static const SteinerTestCase steiner_test_cases[] = {
  {"steiner_grid4x4_t3_corners", 5.0, 10000, 300},
  {"steiner_grid5x5_t4_sparse", 8.0, 10000, 300},
  {"steiner_geom15_r30_t3", 140.14, 10000, 300},
  {"steiner_geom20_r35_t5", 138.48, 10000, 300},
  {"steiner_complete10_unit_t4", 4.0, 10000, 300},
  {"steiner_complete12_rand_t3", 15.0, 10000, 300},
  {"steiner_sparse20_p03_t4", 14.0, 10000, 300},
  {"steiner_sparse25_p025_t6", 45.0, 10000, 300},
};

static const int NUM_TESTS = sizeof(steiner_test_cases) / sizeof(steiner_test_cases[0]);

static int test_steiner(const char *fixture_dir, const SteinerTestCase *tc,
                        MipPerfRecord *perf)
{
  char path[512];
  snprintf(path, sizeof(path), "%s/%s.mps.gz", fixture_dir, tc->name);

  printf("  %s (nodes=%d, expected=%.2f)\n", tc->name, tc->max_nodes, tc->expected_obj);

  perf->name = tc->name; perf->pass = 0; perf->is_optimal = 0;
  perf->nodes = 0; perf->wall_time = 0.0; perf->obj = 1e30;

  Cbc_Model *m = Cbc_newModel();
  Cbc_setLogLevel(m, 0);

  if (Cbc_readMps(m, path) != 0) {
    printf("    FAIL: cannot read %s\n", path);
    Cbc_deleteModel(m);
    return 0;
  }

  Cbc_setMaximumNodes(m, tc->max_nodes);
  double t0 = perf_wall_time();
  Cbc_solve(m);
  perf->wall_time  = perf_wall_time() - t0;
  perf->is_optimal = Cbc_isProvenOptimal(m);
  perf->nodes      = Cbc_getNodeCount(m);

  int pass = 1;
  int nSol = Cbc_numberSavedSolutions(m);

  if (nSol == 0) {
    printf("    FAIL: no feasible solution found (status=%d)\n", Cbc_status(m));
    Cbc_deleteModel(m);
    return 0;
  }

  double obj = Cbc_getObjValue(m);
  perf->obj = obj;

  /* Check feasibility of best and all pool solutions */
  const double *bestSol = Cbc_getColSolution(m);
  double maxViolRow = 0.0; int rowIdx = -1;
  double maxViolCol = 0.0; int colIdx = -1;

  if (!Cbc_checkFeasibility(m, bestSol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
    printf("    FAIL: best solution infeasible  "
           "maxViolRow=%.2e (row %d)  maxViolCol=%.2e (col %d)\n",
           maxViolRow, rowIdx, maxViolCol, colIdx);
    pass = 0;
  }

  for (int s = 0; s < nSol; s++) {
    const double *sol = Cbc_savedSolution(m, s);
    double solObj = Cbc_savedSolutionObj(m, s);
    maxViolRow = 0.0; rowIdx = -1; maxViolCol = 0.0; colIdx = -1;
    if (!Cbc_checkFeasibility(m, sol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
      printf("    FAIL: pool solution %d/%d infeasible (obj=%.2f)  "
             "maxViolRow=%.2e (row %d)  maxViolCol=%.2e (col %d)\n",
             s+1, nSol, solObj, maxViolRow, rowIdx, maxViolCol, colIdx);
      pass = 0;
    }
  }

  /* Only validate objective if solver claims optimality */
  if (perf->is_optimal) {
    double tol = mip_obj_tol(m, tc->expected_obj, 1e-6);
    if (fabs(obj - tc->expected_obj) > tol) {
      printf("    FAIL: proven optimal but obj=%.10g expected=%.10g (tol=%.4g)\n",
             obj, tc->expected_obj, tol);
      pass = 0;
      char tmp_sol[512];
      snprintf(tmp_sol, sizeof(tmp_sol), "/tmp/mipster_diag_%s.sol", tc->name);
      mip_diag_write_sol(m, tmp_sol);
      mip_diag_wrong_optimal(build_mps_model, (void *)path, tc->expected_obj, 300);
      mip_diag_debug_cuts(build_mps_model, (void *)path, tc->expected_obj, 300,
                          tmp_sol, NULL, NULL);
    }
  }

  if (pass) {
    if (perf->is_optimal)
      printf("    PASS obj=%.2f  nodes=%ld  time=%.3fs  (proven optimal)\n",
             obj, perf->nodes, perf->wall_time);
    else
      printf("    PASS obj=%.2f  nodes=%ld  time=%.3fs  (feasible, not proven optimal)\n",
             obj, perf->nodes, perf->wall_time);
  }

  Cbc_deleteModel(m);
  perf->pass = pass;
  return pass;
}

int main(int argc, char **argv)
{
  if (argc < 2) {
    fprintf(stderr, "Usage: %s <fixture-dir>\n", argv[0]);
    return 1;
  }

  const char *fixture_dir = argv[1];

  printf("=== Steiner Tree Tests ===\n");
  int passed = 0, failed = 0;
  MipPerfRecord perf_records[NUM_TESTS];

  for (int i = 0; i < NUM_TESTS; i++) {
    if (test_steiner(fixture_dir, &steiner_test_cases[i], &perf_records[i]))
      passed++;
    else
      failed++;
  }

  print_perf_summary(perf_records, NUM_TESTS, "Steiner Tree");
  printf("\n");
  if (failed == 0)
    printf("=== All %d tests PASSED ===\n", passed);
  else
    printf("=== %d passed, %d FAILED ===\n", passed, failed);

  return (failed == 0) ? 0 : 1;
}
