/* Bin Packing with Conflicts (BPC) tests on generated instances with known optima.

   Formulation:
     minimize   sum_b y[b]
     subject to sum_b x[i][b] = 1              for all i (item i in one bin)
                sum_i w[i] * x[i][b] <= C * y[b]  for all b (capacity)
                x[i][b] + x[j][b] <= y[b]      for all conflicts (i,j)
                x[i][b], y[b] in {0,1}

   Combines knapsack capacity constraints with conflict clique constraints.

   For each solve the solution is verified for:
     - structural feasibility via Cbc_checkFeasibility
     - objective value matches known optimum within tolerance

   Fixtures in fixtures/*.mps.gz (generated by gen_bpp_conflicts_fixtures.py).
   This problem tests both knapsack cuts and clique cuts simultaneously. */

#include "Cbc_C_Interface.h"
#include <math.h>
#include <stdio.h>
#include <string.h>

typedef struct {
  const char *name;
  double expected_obj;
  int timeout_sec;
} BpcTestCase;

static const BpcTestCase bpc_test_cases[] = {
  {"bpc_n10_c100_sd42_random_uniform", 3, 20},
  {"bpc_n12_c150_sd42_clique_diverse", 4, 30},
  {"bpc_n15_c100_sd137_bipartite_uniform", 4, 30},
  {"bpc_n15_c120_sd42_geometric_tight", 5, 40},
  {"bpc_n20_c150_sd42_random_diverse", 6, 90},
  {"bpc_n25_c200_sd137_clique_uniform", 6, 120},
  {"bpc_n30_c180_sd42_geometric_tight", 10, 120},
};

static const int NUM_TESTS = sizeof(bpc_test_cases) / sizeof(bpc_test_cases[0]);

static int test_bpc(const char *fixture_dir, const BpcTestCase *tc)
{
  char path[512];
  snprintf(path, sizeof(path), "%s/%s.mps.gz", fixture_dir, tc->name);

  printf("  %s (timeout=%ds, expected=%.0f bins)\n", tc->name, tc->timeout_sec, tc->expected_obj);

  Cbc_Model *m = Cbc_newModel();
  Cbc_setLogLevel(m, 0);

  if (Cbc_readMps(m, path) != 0) {
    printf("    FAIL: cannot read %s\n", path);
    Cbc_deleteModel(m);
    return 0;
  }

  Cbc_setMaximumSeconds(m, tc->timeout_sec);
  Cbc_solve(m);

  int pass = 1;

  if (!Cbc_isProvenOptimal(m)) {
    printf("    FAIL: not proven optimal (status=%d, sols=%d)\n",
           Cbc_status(m), Cbc_numberSavedSolutions(m));
    pass = 0;
  }

  /* Check feasibility of best solution */
  const double *bestSol = Cbc_getColSolution(m);
  double maxViolRow = 0.0; int rowIdx = -1;
  double maxViolCol = 0.0; int colIdx = -1;

  if (!Cbc_checkFeasibility(m, bestSol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
    printf("    FAIL: best solution infeasible  "
           "maxViolRow=%.2e (row %d)  maxViolCol=%.2e (col %d)\n",
           maxViolRow, rowIdx, maxViolCol, colIdx);
    pass = 0;
  }

  /* Check feasibility of ALL solutions in the pool */
  int nSol = Cbc_numberSavedSolutions(m);
  for (int s = 0; s < nSol; s++) {
    const double *sol = Cbc_savedSolution(m, s);
    double solObj = Cbc_savedSolutionObj(m, s);
    maxViolRow = 0.0; rowIdx = -1;
    maxViolCol = 0.0; colIdx = -1;

    if (!Cbc_checkFeasibility(m, sol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
      printf("    FAIL: pool solution %d/%d infeasible (obj=%.2f)  "
             "maxViolRow=%.2e (row %d)  maxViolCol=%.2e (col %d)\n",
             s+1, nSol, solObj, maxViolRow, rowIdx, maxViolCol, colIdx);
      pass = 0;
    }
  }

  double obj = Cbc_getObjValue(m);
  /* Integer objective (number of bins), check within 0.5 */
  if (fabs(obj - tc->expected_obj) > 0.5) {
    printf("    FAIL: obj=%.0f expected=%.0f\n", obj, tc->expected_obj);
    pass = 0;

    if (Cbc_isProvenOptimal(m)) {
    }
  }

  if (pass) {
    printf("    PASS obj=%.0f bins\n", obj);
  }

  Cbc_deleteModel(m);
  return pass;
}

int main(int argc, char **argv)
{
  if (argc < 2) {
    fprintf(stderr, "Usage: %s <fixture-dir>\n", argv[0]);
    return 1;
  }

  const char *fixture_dir = argv[1];

  printf("=== Bin Packing with Conflicts Tests ===\n");
  int passed = 0, failed = 0;

  for (int i = 0; i < NUM_TESTS; i++) {
    if (test_bpc(fixture_dir, &bpc_test_cases[i])) {
      passed++;
    } else {
      failed++;
    }
  }

  printf("\n");
  if (failed == 0) {
    printf("=== All %d tests PASSED ===\n", passed);
  } else {
    printf("=== %d passed, %d FAILED ===\n", passed, failed);
  }

  return (failed == 0) ? 0 : 1;
}
