/* TSP tests on randomly generated instances with cross-validated optima.
   Two formulations tested per instance:
     1. Miller-Tucker-Zemlin (MTZ) compact formulation — directed arcs
     2. Branch-and-cut with subtour elimination via Cbc_addCutCallback —
        callback fires on integer solutions (lazy-constraint style), adds
        globally-valid SECs using OsiCuts_addGlobalRowCut.
   Fixture data in tsp_fixtures.h (generated by gen_tsp_fixtures.py).
   No external files or data packages required. */

#include "Cbc_C_Interface.h"
#include <assert.h>
#include <math.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "tsp_fixtures.h"

#define MAX_N    25
#define MAX_ARCS (MAX_N * MAX_N)

/* ------------------------------------------------------------------ */
/* MTZ compact formulation (directed arcs)                             */
/* Variables: y[i][j] binary for i!=j; u[i] continuous for i=1..n-1  */
/* MTZ: u[i] - u[j] + n*y[i][j] <= n-1  (i,j >= 1, i!=j)           */
/* ------------------------------------------------------------------ */
static void test_mtz(const TspInstance *inst)
{
  int n = inst->n;
  const int *d = inst->dist;
  printf("  MTZ n=%d seed=%d expected=%d\n", n, inst->seed, inst->opt);

  Cbc_Model *m = Cbc_newModel();
  Cbc_setObjSense(m, 1.0);
  Cbc_setLogLevel(m, 0);

  /* Arc variables y[i][j] for i!=j, binary */
  int y[MAX_N][MAX_N]; /* column index, -1 on diagonal */
  int nArc = 0;
  for (int i = 0; i < n; i++) {
    for (int j = 0; j < n; j++) {
      if (i == j) { y[i][j] = -1; continue; }
      char name[24]; snprintf(name, sizeof(name), "y(%d,%d)", i, j);
      Cbc_addCol(m, name, 0.0, 1.0, (double)d[i * n + j], 1, 0, NULL, NULL);
      y[i][j] = nArc++;
    }
  }

  /* Position variables u[i] for i=1..n-1, continuous in [1, n-1] */
  int u[MAX_N];
  for (int i = 1; i < n; i++) {
    char name[24]; snprintf(name, sizeof(name), "u(%d)", i);
    Cbc_addCol(m, name, 1.0, (double)(n - 1), 0.0, 0, 0, NULL, NULL);
    u[i] = nArc + (i - 1);
  }

  /* Out-degree: sum_j y[i][j] = 1 for each i */
  for (int i = 0; i < n; i++) {
    int idx[MAX_N]; double coef[MAX_N]; int cnt = 0;
    for (int j = 0; j < n; j++) {
      if (j == i) continue;
      idx[cnt] = y[i][j]; coef[cnt] = 1.0; cnt++;
    }
    char name[24]; snprintf(name, sizeof(name), "out(%d)", i);
    Cbc_addRow(m, name, cnt, idx, coef, 'E', 1.0);
  }

  /* In-degree: sum_i y[i][j] = 1 for each j */
  for (int j = 0; j < n; j++) {
    int idx[MAX_N]; double coef[MAX_N]; int cnt = 0;
    for (int i = 0; i < n; i++) {
      if (i == j) continue;
      idx[cnt] = y[i][j]; coef[cnt] = 1.0; cnt++;
    }
    char name[24]; snprintf(name, sizeof(name), "in(%d)", j);
    Cbc_addRow(m, name, cnt, idx, coef, 'E', 1.0);
  }

  /* MTZ: u[i] - u[j] + n*y[i][j] <= n-1  for i,j in 1..n-1, i!=j */
  for (int i = 1; i < n; i++) {
    for (int j = 1; j < n; j++) {
      if (i == j) continue;
      int idx[3]; double coef[3];
      idx[0] = u[i];    coef[0] =  1.0;
      idx[1] = u[j];    coef[1] = -1.0;
      idx[2] = y[i][j]; coef[2] =  (double)n;
      char name[24]; snprintf(name, sizeof(name), "mtz(%d,%d)", i, j);
      Cbc_addRow(m, name, 3, idx, coef, 'L', (double)(n - 1));
    }
  }

  Cbc_solve(m);
  assert(Cbc_isProvenOptimal(m));

  /* Check feasibility of best solution */
  {
    double maxViolRow, maxViolCol; int rowIdx, colIdx;
    int feas = Cbc_checkFeasibility(m, Cbc_getColSolution(m),
                                    &maxViolRow, &rowIdx, &maxViolCol, &colIdx);
    if (!feas) {
      printf("    FAIL: best solution infeasible — rowViol=%.2e (row %d) colViol=%.2e (col %d)\n",
             maxViolRow, rowIdx, maxViolCol, colIdx);
      assert(feas);
    }
  }

  /* Check feasibility of ALL solutions in the pool */
  int nSol = Cbc_numberSavedSolutions(m);
  for (int s = 0; s < nSol; s++) {
    const double *sol = Cbc_savedSolution(m, s);
    double solObj = Cbc_savedSolutionObj(m, s);
    double maxViolRow = 0.0, maxViolCol = 0.0;
    int rowIdx = -1, colIdx = -1;

    if (!Cbc_checkFeasibility(m, sol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
      printf("    FAIL: pool solution %d/%d infeasible (obj=%.0f) — "
             "rowViol=%.2e (row %d) colViol=%.2e (col %d)\n",
             s+1, nSol, solObj, maxViolRow, rowIdx, maxViolCol, colIdx);
      assert(0);
    }
  }

  int obj = (int)round(Cbc_getObjValue(m));
  printf("    -> MTZ obj=%d %s\n", obj, obj == inst->opt ? "OK" : "FAIL");
  assert(obj == inst->opt);
  Cbc_deleteModel(m);
}

/* ------------------------------------------------------------------ */
/* Subtour elimination via cut callback (lazy-constraint style)        */
/*                                                                     */
/* Arc variables are named "x(i,j)" so the callback can identify them */
/* even after preprocessing renames/reorders columns. The callback     */
/* fires on integer solutions (atSolution=1) and adds globally-valid   */
/* subtour elimination constraints via OsiCuts_addGlobalRowCut.       */
/* ------------------------------------------------------------------ */

/* Parse "x(i,j)" -> sets *u=i, *v=j; returns 1 on success */
static int parse_arc_name(const char *name, int *u, int *v)
{
  const char *s = strstr(name, "x(");
  if (!s) return 0;
  s += 2;
  char *end;
  *u = (int)strtol(s, &end, 10);
  if (*end != ',') return 0;
  *v = (int)strtol(end + 1, &end, 10);
  if (*end != ')') return 0;
  return 1;
}

/* BFS: find smallest connected component in the integer arc support.
   Directed arcs treated as undirected for connectivity.
   Returns component size; fills sub[] with node indices. */
static int find_min_subtour_cb(int n, double **xs, int *sub)
{
  int adj[MAX_N][MAX_N], deg[MAX_N];
  memset(deg, 0, sizeof(deg));
  for (int i = 0; i < n; i++) {
    for (int j = 0; j < n; j++) {
      if (i != j && xs[i][j] > 0.5) {
        adj[i][deg[i]++] = j;
        adj[j][deg[j]++] = i; /* undirected BFS */
      }
    }
  }
  int visited[MAX_N]; memset(visited, 0, sizeof(visited));
  int best[MAX_N], best_sz = n + 1;
  for (int start = 0; start < n; start++) {
    if (visited[start]) continue;
    int comp[MAX_N], sz = 0;
    int q[MAX_N], qh = 0, qt = 0;
    q[qt++] = start; visited[start] = 1;
    while (qh < qt) {
      int v = q[qh++]; comp[sz++] = v;
      for (int k = 0; k < deg[v]; k++) {
        int w = adj[v][k];
        if (!visited[w]) { visited[w] = 1; q[qt++] = w; }
      }
    }
    if (sz < best_sz) { best_sz = sz; memcpy(best, comp, sz * sizeof(int)); }
  }
  memcpy(sub, best, best_sz * sizeof(int));
  return best_sz;
}

/* Cut callback: called by CBC on integer solutions.
   appdata points to int n (number of cities). */
static void subtour_cut_cb(void *osiSolver, void *osiCuts, void *appdata,
  int level, int pass)
{
  if (!Osi_isProvenOptimal(osiSolver)) return;

  int n = *((int *)appdata);
  int ncols = Osi_getNumCols(osiSolver);
  const double *x = Osi_getColSolution(osiSolver);

  /* Build n×n arc-value matrix from the solution, parsing variable names */
  double **xs = malloc(sizeof(double *) * n);
  xs[0] = calloc(n * n, sizeof(double));
  for (int i = 1; i < n; i++) xs[i] = xs[0] + i * n;

  int nFrac = 0;
  for (int k = 0; k < ncols; k++) {
    if (x[k] <= 1e-5) continue;
    char vname[64] = "";
    Osi_getColName(osiSolver, k, vname, sizeof(vname));
    int u, v;
    if (!parse_arc_name(vname, &u, &v)) continue;
    if (u < 0 || u >= n || v < 0 || v >= n) continue;
    xs[u][v] = x[k];
    if (fabs(x[k] - round(x[k])) > 1e-5) nFrac++;
  }

  /* Only add lazy SECs on integer solutions */
  if (nFrac > 0) goto done;

  {
    int sub[MAX_N];
    int sz = find_min_subtour_cb(n, xs, sub);
    if (sz == n) goto done; /* valid Hamiltonian cycle, no cut needed */

    /* Mark nodes in the subtour */
    char inSub[MAX_N]; memset(inSub, 0, n);
    for (int k = 0; k < sz; k++) inSub[sub[k]] = 1;

    /* Scan ALL columns by name: include every arc x(u,v) with u,v in subtour.
       We must not filter by current value — zero-valued arcs must appear in
       the SEC so the solver knows they cannot all be 0 simultaneously. */
    int cutIdx[MAX_ARCS]; double cutCoef[MAX_ARCS]; int nz = 0;
    for (int k = 0; k < ncols; k++) {
      char vname[64] = "";
      Osi_getColName(osiSolver, k, vname, sizeof(vname));
      int u, v;
      if (!parse_arc_name(vname, &u, &v)) continue;
      if (u < 0 || u >= n || v < 0 || v >= n) continue;
      if (inSub[u] && inSub[v]) {
        cutIdx[nz] = k;
        cutCoef[nz] = 1.0;
        nz++;
      }
    }
    if (nz > 0)
      OsiCuts_addGlobalRowCut(osiCuts, nz, cutIdx, cutCoef, 'L', (double)(sz - 1));
  }

done:
  free(xs[0]);
  free(xs);
}

static void test_subtour(const TspInstance *inst)
{
  int n = inst->n;
  const int *d = inst->dist;
  printf("  Subtour-elim n=%d seed=%d expected=%d\n", n, inst->seed, inst->opt);

  Cbc_Model *m = Cbc_newModel();
  Cbc_setObjSense(m, 1.0);
  Cbc_setLogLevel(m, 0);

  /* Directed arc variables x(i,j) for i!=j, binary */
  int nArcs = 0;
  for (int i = 0; i < n; i++) {
    for (int j = 0; j < n; j++) {
      if (i == j) continue;
      char name[24]; snprintf(name, sizeof(name), "x(%d,%d)", i, j);
      Cbc_addCol(m, name, 0.0, 1.0, (double)d[i * n + j], 1, 0, NULL, NULL);
      nArcs++;
    }
  }

  /* Out-degree = 1 and in-degree = 1 for each node */
  for (int node = 0; node < n; node++) {
    int idx[MAX_N]; double coef[MAX_N]; int cnt;
    char name[24];
    /* Arc index: x(i,j) is column i*(n-1) + (j<i?j:j-1)
       Easier: iterate and check from/to */
    cnt = 0;
    int col = 0;
    for (int i = 0; i < n; i++) {
      for (int j = 0; j < n; j++) {
        if (i == j) continue;
        if (i == node) { idx[cnt] = col; coef[cnt] = 1.0; cnt++; }
        col++;
      }
    }
    snprintf(name, sizeof(name), "out(%d)", node);
    Cbc_addRow(m, name, cnt, idx, coef, 'E', 1.0);

    cnt = 0; col = 0;
    for (int i = 0; i < n; i++) {
      for (int j = 0; j < n; j++) {
        if (i == j) continue;
        if (j == node) { idx[cnt] = col; coef[cnt] = 1.0; cnt++; }
        col++;
      }
    }
    snprintf(name, sizeof(name), "in(%d)", node);
    Cbc_addRow(m, name, cnt, idx, coef, 'E', 1.0);
  }

  /* Register cut callback: fires on integer solutions (atSolution=1) */
  Cbc_addCutCallback(m, subtour_cut_cb, "TSP-SEC", (void *)&n, 1, 1);

  Cbc_solve(m);
  assert(Cbc_isProvenOptimal(m));

  /* Check feasibility of best solution */
  {
    double maxViolRow, maxViolCol; int rowIdx, colIdx;
    int feas = Cbc_checkFeasibility(m, Cbc_getColSolution(m),
                                    &maxViolRow, &rowIdx, &maxViolCol, &colIdx);
    if (!feas) {
      printf("    FAIL: best solution infeasible — rowViol=%.2e (row %d) colViol=%.2e (col %d)\n",
             maxViolRow, rowIdx, maxViolCol, colIdx);
      assert(feas);
    }
  }

  /* Check feasibility of ALL solutions in the pool */
  int nSol = Cbc_numberSavedSolutions(m);
  for (int s = 0; s < nSol; s++) {
    const double *sol = Cbc_savedSolution(m, s);
    double solObj = Cbc_savedSolutionObj(m, s);
    double maxViolRow = 0.0, maxViolCol = 0.0;
    int rowIdx = -1, colIdx = -1;

    if (!Cbc_checkFeasibility(m, sol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
      printf("    FAIL: pool solution %d/%d infeasible (obj=%.0f) — "
             "rowViol=%.2e (row %d) colViol=%.2e (col %d)\n",
             s+1, nSol, solObj, maxViolRow, rowIdx, maxViolCol, colIdx);
      assert(0);
    }
  }

  int obj = (int)round(Cbc_getObjValue(m));
  printf("    -> Subtour obj=%d %s\n", obj, obj == inst->opt ? "OK" : "FAIL");
  assert(obj == inst->opt);
  Cbc_deleteModel(m);
}

/* ------------------------------------------------------------------ */

int main(void)
{
  printf("=== TSP Random Instance Tests ===\n");
  printf("    %d instances, two formulations each (MTZ + subtour elimination)\n\n",
    N_TSP_INSTANCES);

  for (int i = 0; i < N_TSP_INSTANCES; i++) {
    const TspInstance *inst = &TSP_INSTANCES[i];
    printf("[%d/%d] n=%d seed=%d opt=%d\n",
      i + 1, N_TSP_INSTANCES, inst->n, inst->seed, inst->opt);
    if (inst->n <= 15) /* MTZ LP relaxation is weak for large n; skip n=20 */
      test_mtz(inst);
    test_subtour(inst);
    printf("\n");
  }

  printf("=== All TSP random tests PASSED ===\n");
  return 0;
}
