/* Quadratic Assignment Problem (QAP) tests on generated instances with known optima.

   Formulation (Kaufman-Broeckx linearization):
     minimize   sum_i sum_j sum_k sum_l f[i][j] * d[k][l] * y[i][k][j][l]
     subject to sum_j x[i][j] = 1   for all i (facility i to one location)
                sum_i x[i][j] = 1   for all j (location j used once)
                y[i][k][j][l] >= x[i][k] + x[j][l] - 1   (McCormick linearization)
                x[i][j], y[i][k][j][l] in {0,1}

   Classic quadratic assignment problem, linearized to test MIP solver on
   pure binary formulation with assignment + McCormick constraints.

   For each solve the solution is verified for:
     - structural feasibility via Cbc_checkFeasibility
     - objective value matches known optimum within relative tolerance

   Fixtures in fixtures/*.mps.gz (generated by gen_qap_fixtures.py).
   Includes diverse flow patterns (uniform/sparse/hub) and distance types
   (euclidean/manhattan/grid). */

#include "Cbc_C_Interface.h"
#include <math.h>
#include <stdio.h>
#include <string.h>

typedef struct {
  const char *name;
  double expected_obj;
  int timeout_sec;
} QapTestCase;

static const QapTestCase qap_test_cases[] = {
  {"qap_n4_s42_uniform_euclidean", 5809.00, 10},
  {"qap_n5_s42_uniform_euclidean", 11653.00, 30},
  {"qap_n5_s137_sparse_manhattan", 6070.00, 30},
  {"qap_n6_s42_uniform_grid", 457.00, 60},
  {"qap_n6_s137_hub_euclidean", 20623.00, 60},
  {"qap_n7_s42_uniform_euclidean", 22834.00, 120},
  {"qap_n7_s137_sparse_grid", 239.00, 120},
};

static const int NUM_TESTS = sizeof(qap_test_cases) / sizeof(qap_test_cases[0]);

static int test_qap(const char *fixture_dir, const QapTestCase *tc)
{
  char path[512];
  snprintf(path, sizeof(path), "%s/%s.mps.gz", fixture_dir, tc->name);

  printf("  %s (timeout=%ds, expected=%.0f)\n", tc->name, tc->timeout_sec, tc->expected_obj);

  Cbc_Model *m = Cbc_newModel();
  Cbc_setLogLevel(m, 0);

  if (Cbc_readMps(m, path) != 0) {
    printf("    FAIL: cannot read %s\n", path);
    Cbc_deleteModel(m);
    return 0;
  }

  Cbc_setMaximumSeconds(m, tc->timeout_sec);
  Cbc_solve(m);

  int pass = 1;

  if (!Cbc_isProvenOptimal(m)) {
    printf("    FAIL: not proven optimal (status=%d, sols=%d)\n",
           Cbc_status(m), Cbc_numberSavedSolutions(m));
    pass = 0;
  }

  const double *sol = Cbc_getColSolution(m);
  double maxViolRow = 0.0; int rowIdx = -1;
  double maxViolCol = 0.0; int colIdx = -1;

  if (!Cbc_checkFeasibility(m, sol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
    printf("    FAIL: Cbc_checkFeasibility failed  "
           "maxViolRow=%.2e (row %d)  maxViolCol=%.2e (col %d)\n",
           maxViolRow, rowIdx, maxViolCol, colIdx);
    pass = 0;
  }

  double obj = Cbc_getObjValue(m);
  double rel_err = fabs(obj - tc->expected_obj) / fmax(fabs(tc->expected_obj), 1.0);

  if (rel_err > 1e-3) {
    printf("    FAIL: obj=%.2f expected=%.2f (rel_err=%.2e)\n",
           obj, tc->expected_obj, rel_err);
    pass = 0;

  }

  if (pass) {
    printf("    PASS obj=%.0f\n", obj);
  }

  Cbc_deleteModel(m);
  return pass;
}

int main(int argc, char **argv)
{
  if (argc < 2) {
    fprintf(stderr, "Usage: %s <fixture-dir>\n", argv[0]);
    return 1;
  }

  const char *fixture_dir = argv[1];

  printf("=== Quadratic Assignment Problem Tests ===\n");
  int passed = 0, failed = 0;

  for (int i = 0; i < NUM_TESTS; i++) {
    if (test_qap(fixture_dir, &qap_test_cases[i])) {
      passed++;
    } else {
      failed++;
    }
  }

  printf("\n");
  if (failed == 0) {
    printf("=== All %d tests PASSED ===\n", passed);
  } else {
    printf("=== %d passed, %d FAILED ===\n", passed, failed);
  }

  return (failed == 0) ? 0 : 1;
}
