/* Set Packing Problem (SPP) tests on generated instances with known optima.

   Formulation (maximization):
     maximize   sum_j v[j] * x[j]
     subject to sum_{j: i in S[j]} x[j] <= 1   for all i (element i in at most one set)
                x[j] in {0,1}

   Equivalent to maximum weighted independent set in the conflict graph.

   For each solve the solution is verified for:
     - structural feasibility via Cbc_checkFeasibility
     - objective value matches known optimum within relative tolerance

   Fixtures in fixtures/*.mps.gz (generated by gen_setpacking_fixtures.py).
   This problem tests clique cut generation on packing/conflict structures. */

#include "Cbc_C_Interface.h"
#include "mip_diag.h"
#include "test_utils.h"
#include <math.h>
#include <stdio.h>
#include <string.h>

typedef struct {
  const char *name;
  double expected_obj;
  int max_nodes;
  int timeout_sec;  /* Fallback */
} SetPackingTestCase;

static const SetPackingTestCase setpacking_test_cases[] = {
  {"spp_e10_s15_sd42_random", 302.00, 10000, 300},
  {"spp_e12_s18_sd42_k_partite", 111.00, 10000, 300},
  {"spp_e15_s20_sd137_geometric", 314.00, 10000, 300},
  {"spp_e20_s25_sd42_scheduling", 355.00, 10000, 300},
  {"spp_e30_s50_sd42_random", 652.00, 10000, 300},
  {"spp_e35_s60_sd137_k_partite", 238.00, 10000, 300},
  {"spp_e40_s70_sd42_geometric", 986.00, 10000, 300},
  {"spp_e50_s80_sd137_scheduling", 1039.00, 10000, 300},
};

static const int NUM_TESTS = sizeof(setpacking_test_cases) / sizeof(setpacking_test_cases[0]);

static int test_setpacking(const char *fixture_dir, const SetPackingTestCase *tc,
                            MipPerfRecord *perf)
{
  char path[512];
  snprintf(path, sizeof(path), "%s/%s.mps.gz", fixture_dir, tc->name);

  printf("  %s (nodes=%d, expected=%.0f)\n", tc->name, tc->max_nodes, tc->expected_obj);

  perf->name = tc->name; perf->pass = 0; perf->is_optimal = 0;
  perf->nodes = 0; perf->wall_time = 0.0; perf->obj = 1e30;

  Cbc_Model *m = Cbc_newModel();
  Cbc_setLogLevel(m, 0);

  if (Cbc_readMps(m, path) != 0) {
    printf("    FAIL: cannot read %s\n", path);
    Cbc_deleteModel(m);
    return 0;
  }

  Cbc_setMaximumNodes(m, tc->max_nodes);
  double t0 = perf_wall_time();
  Cbc_solve(m);
  perf->wall_time  = perf_wall_time() - t0;
  perf->is_optimal = Cbc_isProvenOptimal(m);
  perf->nodes      = Cbc_getNodeCount(m);

  int pass = 1;
  int nSol = Cbc_numberSavedSolutions(m);

  if (nSol == 0) {
    printf("    FAIL: no feasible solution found (status=%d)\n", Cbc_status(m));
    Cbc_deleteModel(m);
    return 0;
  }

  /* MPS file has negated objective for maximization */
  double obj = -Cbc_getObjValue(m);
  perf->obj = obj;

  /* Check feasibility of best and all pool solutions */
  const double *bestSol = Cbc_getColSolution(m);
  double maxViolRow = 0.0; int rowIdx = -1;
  double maxViolCol = 0.0; int colIdx = -1;

  if (!Cbc_checkFeasibility(m, bestSol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
    printf("    FAIL: best solution infeasible  "
           "maxViolRow=%.2e (row %d)  maxViolCol=%.2e (col %d)\n",
           maxViolRow, rowIdx, maxViolCol, colIdx);
    pass = 0;
  }

  for (int s = 0; s < nSol; s++) {
    const double *sol = Cbc_savedSolution(m, s);
    double solObj = Cbc_savedSolutionObj(m, s);
    maxViolRow = 0.0; rowIdx = -1; maxViolCol = 0.0; colIdx = -1;
    if (!Cbc_checkFeasibility(m, sol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
      printf("    FAIL: pool solution %d/%d infeasible (obj=%.2f)  "
             "maxViolRow=%.2e (row %d)  maxViolCol=%.2e (col %d)\n",
             s+1, nSol, solObj, maxViolRow, rowIdx, maxViolCol, colIdx);
      pass = 0;
    }
  }

  /* Only validate objective if solver claims optimality */
  if (perf->is_optimal) {
    double rel_err = fabs(obj - tc->expected_obj) / fmax(fabs(tc->expected_obj), 1.0);
    if (rel_err > 1e-3) {
      printf("    FAIL: proven optimal but obj=%.2f expected=%.2f (rel_err=%.2e)\n",
             obj, tc->expected_obj, rel_err);
      pass = 0;
      /* MPS stores negated maximization objective; diag uses raw model values */
      char tmp_sol[512];
      snprintf(tmp_sol, sizeof(tmp_sol), "/tmp/mipster_diag_%s.sol", tc->name);
      mip_diag_write_sol(m, tmp_sol);
      mip_diag_wrong_optimal(build_mps_model, (void *)path, -tc->expected_obj, 300);
      mip_diag_debug_cuts(build_mps_model, (void *)path, -tc->expected_obj, 300,
                          tmp_sol, NULL, NULL);
    }
  }

  if (pass) {
    if (perf->is_optimal)
      printf("    PASS obj=%.0f  nodes=%ld  time=%.3fs  (proven optimal)\n",
             obj, perf->nodes, perf->wall_time);
    else
      printf("    PASS obj=%.0f  nodes=%ld  time=%.3fs  (feasible, not proven optimal)\n",
             obj, perf->nodes, perf->wall_time);
  }

  Cbc_deleteModel(m);
  perf->pass = pass;
  return pass;
}

int main(int argc, char **argv)
{
  if (argc < 2) {
    fprintf(stderr, "Usage: %s <fixture-dir>\n", argv[0]);
    return 1;
  }

  const char *fixture_dir = argv[1];

  printf("=== Set Packing Tests ===\n");
  int passed = 0, failed = 0;
  MipPerfRecord perf_records[NUM_TESTS];

  for (int i = 0; i < NUM_TESTS; i++) {
    if (test_setpacking(fixture_dir, &setpacking_test_cases[i], &perf_records[i]))
      passed++;
    else
      failed++;
  }

  print_perf_summary(perf_records, NUM_TESTS, "Set Packing");
  printf("\n");
  if (failed == 0)
    printf("=== All %d tests PASSED ===\n", passed);
  else
    printf("=== %d passed, %d FAILED ===\n", passed, failed);

  return (failed == 0) ? 0 : 1;
}

