/* Set Partitioning Problem tests on generated instances with known optima.

   Formulation:
     minimize   sum_j c[j] * x[j]
     subject to sum_{j: i in S[j]} x[j] = 1   for all i (element i in exactly one set)
                x[j] in {0,1}

   Stricter than set covering (= vs >=), tests equality constraints and
   highly degenerate structures (many optimal solutions).

   For each solve the solution is verified for:
     - structural feasibility via Cbc_checkFeasibility
     - objective value matches known optimum within relative tolerance

   Fixtures in fixtures/*.mps.gz (generated by gen_setpartitioning_fixtures.py).
   This problem tests clique cuts and preprocessing on partitioning structures. */

#include "Cbc_C_Interface.h"
#include <math.h>
#include <stdio.h>
#include <string.h>

typedef struct {
  const char *name;
  double expected_obj;
  int timeout_sec;
} SetPartitioningTestCase;

static const SetPartitioningTestCase setpartitioning_test_cases[] = {
  {"sprt_e10_s20_sd42_uniform", 192.00, 10},
  {"sprt_e15_s30_sd42_overlapping", 125.00, 20},
  {"sprt_e30_s60_sd42_uniform", 629.00, 60},
  {"sprt_e40_s80_sd137_overlapping", 744.00, 90},
};

static const int NUM_TESTS = sizeof(setpartitioning_test_cases) / sizeof(setpartitioning_test_cases[0]);

static int test_setpartitioning(const char *fixture_dir, const SetPartitioningTestCase *tc)
{
  char path[512];
  snprintf(path, sizeof(path), "%s/%s.mps.gz", fixture_dir, tc->name);

  printf("  %s (timeout=%ds, expected=%.0f)\n", tc->name, tc->timeout_sec, tc->expected_obj);

  Cbc_Model *m = Cbc_newModel();
  Cbc_setLogLevel(m, 0);

  if (Cbc_readMps(m, path) != 0) {
    printf("    FAIL: cannot read %s\n", path);
    Cbc_deleteModel(m);
    return 0;
  }

  Cbc_setMaximumSeconds(m, tc->timeout_sec);
  Cbc_solve(m);

  int pass = 1;

  if (!Cbc_isProvenOptimal(m)) {
    printf("    FAIL: not proven optimal (status=%d, sols=%d)\n",
           Cbc_status(m), Cbc_numberSavedSolutions(m));
    pass = 0;
  }

  const double *sol = Cbc_getColSolution(m);
  double maxViolRow = 0.0; int rowIdx = -1;
  double maxViolCol = 0.0; int colIdx = -1;

  if (!Cbc_checkFeasibility(m, sol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
    printf("    FAIL: Cbc_checkFeasibility failed  "
           "maxViolRow=%.2e (row %d)  maxViolCol=%.2e (col %d)\n",
           maxViolRow, rowIdx, maxViolCol, colIdx);
    pass = 0;
  }

  double obj = Cbc_getObjValue(m);
  double rel_err = fabs(obj - tc->expected_obj) / fmax(fabs(tc->expected_obj), 1.0);

  if (rel_err > 1e-3) {
    printf("    FAIL: obj=%.2f expected=%.2f (rel_err=%.2e)\n",
           obj, tc->expected_obj, rel_err);
    pass = 0;

  }

  if (pass) {
    printf("    PASS obj=%.0f\n", obj);
  }

  Cbc_deleteModel(m);
  return pass;
}

int main(int argc, char **argv)
{
  if (argc < 2) {
    fprintf(stderr, "Usage: %s <fixture-dir>\n", argv[0]);
    return 1;
  }

  const char *fixture_dir = argv[1];

  printf("=== Set Partitioning Tests ===\n");
  int passed = 0, failed = 0;

  for (int i = 0; i < NUM_TESTS; i++) {
    if (test_setpartitioning(fixture_dir, &setpartitioning_test_cases[i])) {
      passed++;
    } else {
      failed++;
    }
  }

  printf("\n");
  if (failed == 0) {
    printf("=== All %d tests PASSED ===\n", passed);
  } else {
    printf("=== %d passed, %d FAILED ===\n", passed, failed);
  }

  return (failed == 0) ? 0 : 1;
}
