/* Job Shop Scheduling Problem (JSSP) tests on classic benchmark instances.

   JSSP formulation (disjunctive/big-M):
     minimize   C (makespan)
     subject to x[j][op] + p[j][op] <= x[j][op+1]           (precedence within job)
                x[j][op_j] + p[j][op_j] <= x[k][op_k] + M*(1 - y[j][k][m])  (disjunctive)
                x[k][op_k] + p[k][op_k] <= x[j][op_j] + M*y[j][k][m]
                x[j][last_op] + p[j][last_op] <= C          (makespan definition)
                x[j][op] >= 0, y[j][k][m] in {0,1}

   Tests big-M disjunctive constraints, sequencing binaries, and time-indexed
   scheduling formulations.

   For each solve the solution is verified for:
     - structural feasibility via Cbc_checkFeasibility
     - objective value (makespan) matches known optimum within tolerance

   Fixtures from classic JSSP benchmarks (Fisher & Thompson, Lawrence,
   Applegate & Cook) in fixtures/*.mps.gz (generated by gen_jssp_fixtures.py).

   Diversity:
     - Size: 6x6 to 20x5
     - Structures: Fisher & Thompson (balanced), Lawrence (rectangular),
       Applegate & Cook (square with diverse processing times)
     - Processing time distributions
     - Machine orderings */

#include "Cbc_C_Interface.h"
#include <math.h>
#include <stdio.h>
#include <string.h>

typedef struct {
  const char *name;
  double expected_makespan;
  int timeout_sec;
} JsspTestCase;

static const JsspTestCase jssp_test_cases[] = {
  {"jssp_ft06", 55, 30},      /* Fisher & Thompson 6x6 */
  {"jssp_ft10", 930, 300},    /* Fisher & Thompson 10x10 */
  {"jssp_la01", 666, 120},    /* Lawrence 10x5 */
  {"jssp_la06", 926, 180},    /* Lawrence 15x5 */
  {"jssp_la11", 1222, 300},   /* Lawrence 20x5 */
  {"jssp_orb01", 1059, 300},  /* Applegate & Cook 10x10 */
};

static const int NUM_TESTS = sizeof(jssp_test_cases) / sizeof(jssp_test_cases[0]);

static int test_jssp(const char *fixture_dir, const JsspTestCase *tc)
{
  char path[512];
  snprintf(path, sizeof(path), "%s/%s.mps.gz", fixture_dir, tc->name);

  printf("  %s (timeout=%ds, expected makespan=%.0f)\n",
         tc->name, tc->timeout_sec, tc->expected_makespan);

  Cbc_Model *m = Cbc_newModel();
  Cbc_setLogLevel(m, 0);

  if (Cbc_readMps(m, path) != 0) {
    printf("    FAIL: cannot read %s\n", path);
    Cbc_deleteModel(m);
    return 0;
  }

  Cbc_setMaximumSeconds(m, tc->timeout_sec);
  Cbc_solve(m);

  int pass = 1;

  if (!Cbc_isProvenOptimal(m)) {
    printf("    FAIL: not proven optimal (status=%d, sols=%d)\n",
           Cbc_status(m), Cbc_numberSavedSolutions(m));
    pass = 0;
  }

  /* Check feasibility of best solution */
  const double *bestSol = Cbc_getColSolution(m);
  double maxViolRow = 0.0; int rowIdx = -1;
  double maxViolCol = 0.0; int colIdx = -1;

  if (!Cbc_checkFeasibility(m, bestSol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
    printf("    FAIL: best solution infeasible  "
           "maxViolRow=%.2e (row %d)  maxViolCol=%.2e (col %d)\n",
           maxViolRow, rowIdx, maxViolCol, colIdx);
    pass = 0;
  }

  /* Check feasibility of ALL solutions in the pool */
  int nSol = Cbc_numberSavedSolutions(m);
  for (int s = 0; s < nSol; s++) {
    const double *sol = Cbc_savedSolution(m, s);
    double solObj = Cbc_savedSolutionObjective(m, s);
    maxViolRow = 0.0; rowIdx = -1;
    maxViolCol = 0.0; colIdx = -1;

    if (!Cbc_checkFeasibility(m, sol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
      printf("    FAIL: pool solution %d/%d infeasible (obj=%.0f)  "
             "maxViolRow=%.2e (row %d)  maxViolCol=%.2e (col %d)\n",
             s+1, nSol, solObj, maxViolRow, rowIdx, maxViolCol, colIdx);
      pass = 0;
    }
  }

  /* Check best solution objective */
  double makespan = Cbc_getObjValue(m);
  double abs_err = fabs(makespan - tc->expected_makespan);

  /* Integer makespan, check within 0.5 */
  if (abs_err > 0.5) {
    printf("    FAIL: makespan=%.0f expected=%.0f (error=%.1f)\n",
           makespan, tc->expected_makespan, abs_err);
    pass = 0;
  }

  if (pass) {
    printf("    PASS makespan=%.0f\n", makespan);
  }

  Cbc_deleteModel(m);
  return pass;
}

int main(int argc, char **argv)
{
  if (argc < 2) {
    fprintf(stderr, "Usage: %s <fixture-dir>\n", argv[0]);
    return 1;
  }

  const char *fixture_dir = argv[1];

  printf("=== Job Shop Scheduling Tests ===\n");
  int passed = 0, failed = 0;

  for (int i = 0; i < NUM_TESTS; i++) {
    if (test_jssp(fixture_dir, &jssp_test_cases[i])) {
      passed++;
    } else {
      failed++;
    }
  }

  printf("\n");
  if (failed == 0) {
    printf("=== All %d tests PASSED ===\n", passed);
  } else {
    printf("=== %d passed, %d FAILED ===\n", passed, failed);
  }

  return (failed == 0) ? 0 : 1;
}
