/* Multi-Item Capacitated Lot Sizing with Batch Production (MICLSP) tests.
 *
 * Problem structure:
 *   - Binary variables  : y[i,t]  — setup indicator for item i in period t
 *   - Integer variables : n[i,t]  — number of production batches
 *   - Continuous vars   : s[i,t]  — end-of-period inventory
 *
 * Constraints:
 *   Inventory balance : s[i,t-1] + B[i]*n[i,t] - s[i,t] = d[i,t]  (s[i,-1]=0)
 *   Machine capacity  : sum_i B[i]*n[i,t]                <= C[t]
 *   Big-M setup link  : n[i,t]                           <= floor(C[t]/B[i])*y[i,t]
 *
 * Tests verify:
 *   1. MIP solve: Cbc_getObjValue() matches certified optima (exercises postprocessing
 *      path that previously returned a stale pre-postprocessing objective value).
 *   2. Solution feasibility: inventory balance, capacity, integrality, Big-M.
 *   3. Objective computed from solution variables agrees with Cbc_getObjValue().
 *   4. LP relaxation lower bound <= MIP optimum.
 *
 * Fixture data in miclsp_fixtures.h (generated by gen_miclsp_fixtures.py).
 */

#include <assert.h>
#include <string.h>

#include "miclsp_builder.h"
#include "mip_diag.h"
#include "test_utils.h"

/* ── solution checker ─────────────────────────────────────────────────────── */

/* Validates a solution vector for semantic correctness (integrality, inventory
 * balance, capacity, Big-M, and objective consistency).
 * sol_obj is the objective value reported for this solution.
 * Returns 1 on pass, 0 on any violation. */
static int check_miclsp_sol(const double *sol, double sol_obj,
                              const MiclspInstance *inst, const char *label)
{
  int I = inst->I, T = inst->T;
  double s_prev[MAX_I] = {0};

  for (int t = 0; t < T; t++) {
    double cap_used = 0.0;
    for (int i = 0; i < I; i++) {
      double y_it = sol[yidx(T, i, t)];
      double n_it = sol[nidx(I, T, i, t)];
      double s_it = sol[sidx(I, T, i, t)];
      double d_it = (double)inst->d[i * T + t];

      /* y must be binary */
      if (y_it < -1e-6 || y_it > 1.0 + 1e-6 || fabs(y_it - round(y_it)) > 1e-4) {
        printf("    FAIL [%s]: y(%d,%d)=%.6f not binary\n", label, i, t, y_it);
        return 0;
      }

      /* n must be a non-negative integer */
      if (n_it < -1e-6 || fabs(n_it - round(n_it)) > 1e-4) {
        printf("    FAIL [%s]: n(%d,%d)=%.6f not a non-negative integer\n",
               label, i, t, n_it);
        return 0;
      }

      /* Big-M: n[i,t] <= floor(C[t]/B[i]) * y[i,t] */
      int Mv = inst->C[t] / inst->B[i];
      if (n_it > (double)Mv * y_it + 1e-4) {
        printf("    FAIL [%s]: Big-M violated n(%d,%d)=%.1f > %d*y=%.1f\n",
               label, i, t, n_it, Mv, y_it);
        return 0;
      }

      /* Inventory balance: s_prev + B[i]*n[i,t] - s[i,t] = d[i,t] */
      double balance = s_prev[i] + (double)inst->B[i] * n_it - s_it - d_it;
      if (fabs(balance) > 1e-4) {
        printf("    FAIL [%s]: inventory balance violated i=%d t=%d "
               "(residual=%.6f)\n", label, i, t, balance);
        return 0;
      }

      cap_used += (double)inst->B[i] * n_it;
      s_prev[i] = s_it;
    }

    /* Machine capacity */
    if (cap_used > (double)inst->C[t] + 1e-4) {
      printf("    FAIL [%s]: capacity exceeded at t=%d (used=%.1f cap=%d)\n",
             label, t, cap_used, inst->C[t]);
      return 0;
    }
  }

  /* sol_obj must agree with the dot-product computed from the solution */
  double obj_computed = 0.0;
  for (int i = 0; i < I; i++)
    for (int t = 0; t < T; t++) {
      obj_computed += (double)inst->f[i] * sol[yidx(T, i, t)];
      obj_computed += (double)inst->h[i] * sol[sidx(I, T, i, t)];
    }
  if (fabs(sol_obj - obj_computed) > 1.0) {
    printf("    FAIL [%s]: reported obj=%.1f disagrees with "
           "solution dot-product=%.1f\n", label, sol_obj, obj_computed);
    return 0;
  }

  return 1;
}

/* Validates the incumbent (Cbc_getColSolution) via Cbc_checkFeasibility plus
 * check_miclsp_sol.  Returns 1 on pass, 0 on any violation. */
static int check_miclsp_incumbent(Cbc_Model *m, const MiclspInstance *inst,
                                   const char *label)
{
  const double *sol = Cbc_getColSolution(m);
  double maxViolRow, maxViolCol;
  int rowIdx, colIdx;
  if (!Cbc_checkFeasibility(m, sol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
    printf("    FAIL [%s]: Cbc_checkFeasibility — "
           "maxRowViol=%.2e (row %d)  maxColViol=%.2e (col %d)\n",
           label, maxViolRow, rowIdx, maxViolCol, colIdx);
    return 0;
  }
  return check_miclsp_sol(sol, Cbc_getObjValue(m), inst, label);
}

/* ── diagnostic adapter ───────────────────────────────────────────────────── */

static Cbc_Model *build_miclsp_for_diag(void *userdata)
{
  return build_miclsp((const MiclspInstance *)userdata);
}

/* ── MIP test ─────────────────────────────────────────────────────────────── */

static int test_miclsp_mip(const MiclspInstance *inst, int k)
{
  printf("  [%2d] MIP I=%d T=%d rho=%.2f opt=%d\n",
         k + 1, inst->I, inst->T, inst->rho, inst->opt);
  Cbc_Model *m = build_miclsp(inst);
  Cbc_setParameter(m, "seconds", "300");
  Cbc_solve(m);

  int nsaved    = Cbc_numberSavedSolutions(m);
  int is_proven = Cbc_isProvenOptimal(m);
  int ok = 1;

  if (nsaved == 0 && !is_proven) {
    /* No solution found within the time limit — not a failure */
    printf("       -> no solution found (time limit)  SKIP\n");
    Cbc_deleteModel(m);
    return 1;
  }

  /* Validate every saved solution */
  for (int s = 0; s < nsaved; s++) {
    const double *sol = Cbc_savedSolution(m, s);
    double sol_obj    = Cbc_savedSolutionObj(m, s);
    char label[32];
    snprintf(label, sizeof(label), "saved[%d]", s);
    if (!check_miclsp_sol(sol, sol_obj, inst, label)) {
      printf("       -> saved solution %d (obj=%.0f) is INVALID\n", s, sol_obj);
      ok = 0;
    }
  }

  /* Validate the incumbent (best solution) */
  if (!check_miclsp_incumbent(m, inst, "incumbent")) {
    printf("       -> incumbent is INVALID\n");
    ok = 0;
  }

  if (!ok) {
    Cbc_deleteModel(m);
    return 0;
  }

  double obj = Cbc_getObjValue(m);

  if (is_proven) {
    /* Optimality claimed: objective must match certified optimum */
    if (fabs(obj - (double)inst->opt) > 1.0) {
      printf("       -> FAIL: claimed optimal obj=%.0f != certified opt=%d\n",
             obj, inst->opt);
      ok = 0;
      mip_diag_wrong_optimal(build_miclsp_for_diag, (void *)inst,
                             inst->opt, 900);
      mip_diag_debug_cuts(build_miclsp_for_diag, (void *)inst,
                          inst->opt, 900,
                          solution_path(MICLSP_NAMES[k]));
    } else {
      printf("       -> obj=%.0f  optimal, matches certified=%d"
             "  %d solution(s) validated  OK\n", obj, inst->opt, nsaved);
    }
  } else {
    double bound = Cbc_getBestPossibleObjValue(m);
    double gap   = (obj > 1e-10) ? 100.0 * (obj - bound) / obj : 0.0;
    printf("       -> obj=%.0f  bound=%.0f  gap=%.1f%%"
           "  %d solution(s) validated  OK\n", obj, bound, gap, nsaved);
  }

  Cbc_deleteModel(m);
  return ok;
}

/* ── LP relaxation test ───────────────────────────────────────────────────── */

static int test_miclsp_lp(const MiclspInstance *inst, int k)
{
  int I = inst->I, T = inst->T;
  printf("  [%2d] LP  I=%d T=%d rho=%.2f mip_opt=%d\n",
         k + 1, I, T, inst->rho, inst->opt);

  Cbc_Model *m = Cbc_newModel();
  Cbc_setObjSense(m, 1.0);
  Cbc_setLogLevel(m, 0);

  /* y[i,t]: continuous in [0,1] */
  for (int i = 0; i < I; i++)
    for (int t = 0; t < T; t++) {
      char name[32]; snprintf(name, sizeof(name), "y(%d,%d)", i, t);
      Cbc_addCol(m, name, 0.0, 1.0, (double)inst->f[i], 0, 0, NULL, NULL);
    }

  /* n[i,t]: continuous >= 0 */
  for (int i = 0; i < I; i++)
    for (int t = 0; t < T; t++) {
      char name[32]; snprintf(name, sizeof(name), "n(%d,%d)", i, t);
      Cbc_addCol(m, name, 0.0, 1e30, 0.0, 0, 0, NULL, NULL);
    }

  /* s[i,t]: continuous >= 0 */
  for (int i = 0; i < I; i++)
    for (int t = 0; t < T; t++) {
      char name[32]; snprintf(name, sizeof(name), "s(%d,%d)", i, t);
      Cbc_addCol(m, name, 0.0, 1e30, (double)inst->h[i], 0, 0, NULL, NULL);
    }

  /* Inventory balance */
  for (int i = 0; i < I; i++) {
    for (int t = 0; t < T; t++) {
      int idx[3]; double coef[3]; int nz = 0;
      idx[nz] = nidx(I, T, i, t);  coef[nz++] = (double)inst->B[i];
      idx[nz] = sidx(I, T, i, t);  coef[nz++] = -1.0;
      if (t > 0) { idx[nz] = sidx(I, T, i, t - 1); coef[nz++] = 1.0; }
      char name[32]; snprintf(name, sizeof(name), "inv(%d,%d)", i, t);
      miclsp_add_row(m, nz, idx, coef, 'E', (double)inst->d[i * T + t], name);
    }
  }

  /* Machine capacity */
  for (int t = 0; t < T; t++) {
    int idx[MAX_I]; double coef[MAX_I];
    for (int i = 0; i < I; i++) { idx[i] = nidx(I, T, i, t); coef[i] = (double)inst->B[i]; }
    char name[32]; snprintf(name, sizeof(name), "cap(%d)", t);
    miclsp_add_row(m, I, idx, coef, 'L', (double)inst->C[t], name);
  }

  /* Big-M */
  for (int i = 0; i < I; i++)
    for (int t = 0; t < T; t++) {
      int Mv = inst->C[t] / inst->B[i];
      if (Mv <= 0) continue;
      int idx[2]     = { nidx(I, T, i, t), yidx(T, i, t) };
      double coef[2] = { 1.0, -(double)Mv };
      char name[32]; snprintf(name, sizeof(name), "bigm(%d,%d)", i, t);
      miclsp_add_row(m, 2, idx, coef, 'L', 0.0, name);
    }

  int rc = Cbc_solveLinearProgram(m);
  int pass = 1;
  if (rc != 0) {
    printf("       FAIL: LP solve returned %d\n", rc);
    Cbc_deleteModel(m);
    return 0;
  }

  double lp_obj = Cbc_getObjValue(m);
  if (lp_obj > (double)inst->opt + 0.5) {
    printf("       FAIL: LP obj=%.4f > MIP opt=%d\n", lp_obj, inst->opt);
    pass = 0;
  } else {
    printf("       -> LP=%.2f <= MIP=%d  OK\n", lp_obj, inst->opt);
  }
  Cbc_deleteModel(m);
  return pass;
}

/* ── main ─────────────────────────────────────────────────────────────────── */

int main(void)
{
  int nfail = 0;

  printf("=== MICLSP (Multi-Item Capacitated Lot Sizing with Batch Production) ===\n");
  printf("    %d instances: binary (setup) + integer (batches) + continuous (inventory)\n",
         N_MICLSP_INSTANCES);
  printf("    Big-M constraints, preprocessing, postprocessing path exercised.\n\n");

  printf("--- MIP solves ---\n");
  for (int k = 0; k < N_MICLSP_INSTANCES; k++)
    if (!test_miclsp_mip(&MICLSP_INSTANCES[k], k))
      nfail++;

  printf("\n--- LP relaxations ---\n");
  for (int k = 0; k < N_MICLSP_INSTANCES; k++)
    if (!test_miclsp_lp(&MICLSP_INSTANCES[k], k))
      nfail++;

  printf("\n");
  if (nfail == 0)
    printf("=== All MICLSP tests PASSED ===\n");
  else
    printf("=== %d MICLSP test(s) FAILED ===\n", nfail);

  return nfail > 0 ? 1 : 0;
}
