/* Multi-Dimensional Knapsack Problem (MDKP) tests on randomly generated
   instances with known optima.

   Formulation (standard binary IP):
     maximize   sum_j p[j] * x[j]
     subject to sum_j w[i][j] * x[j] <= c[i]   for i = 0..m-1
                x[j] in {0,1}

   For each solve the solution is verified for:
     - structural feasibility via Cbc_checkFeasibility
     - all capacity constraints satisfied within primal tolerance
     - objective value matches known optimum within 0.5

   Fixture data in mdkp_fixtures.h (generated by gen_mdkp_fixtures.py).
   No external files or data packages required. */

#include "Cbc_C_Interface.h"
#include <assert.h>
#include <math.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "mdkp_fixtures.h"

#define MAX_M 12
#define MAX_N 45

/* ── helpers ──────────────────────────────────────────────────────────────── */

static Cbc_Model *new_model(void)
{
  Cbc_Model *m = Cbc_newModel();
  Cbc_setObjSense(m, -1.0);  /* maximise */
  Cbc_setLogLevel(m, 0);
  return m;
}

/* Build and solve one MDKP instance.  Returns 1 on pass. */
static int test_mdkp(const MdkpInstance *inst)
{
  int mm = inst->m, n = inst->n;

  printf("  MDKP m=%d n=%d expected=%d\n", mm, n, inst->opt);

  Cbc_Model *m = new_model();

  /* Item variables x[j], binary, profit as (negated) objective coefficient
     because Cbc_setObjSense(-1) = maximise, so we pass positive profits */
  for (int j = 0; j < n; j++) {
    char name[24]; snprintf(name, sizeof(name), "x(%d)", j);
    Cbc_addCol(m, name, 0.0, 1.0, (double)inst->p[j], 1, 0, NULL, NULL);
  }

  /* Capacity constraints: sum_j w[i][j] * x[j] <= c[i] */
  for (int i = 0; i < mm; i++) {
    int    idx[MAX_N];
    double coef[MAX_N];
    for (int j = 0; j < n; j++) { idx[j] = j; coef[j] = (double)inst->w[i * n + j]; }
    char name[24]; snprintf(name, sizeof(name), "cap(%d)", i);
    Cbc_addRow(m, name, n, idx, coef, 'L', (double)inst->c[i]);
  }

  Cbc_solve(m);

  int pass = 1;

  if (!Cbc_isProvenOptimal(m)) {
    printf("    FAIL: solver did not prove optimality\n");
    Cbc_deleteModel(m);
    return 0;
  }

  /* Structural check: feasibility and integrality */
  const double *sol = Cbc_getColSolution(m);
  double maxViolRow = 0.0; int rowIdx = -1;
  double maxViolCol = 0.0; int colIdx = -1;
  if (!Cbc_checkFeasibility(m, sol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
    printf("    FAIL: Cbc_checkFeasibility failed  "
           "maxViolRow=%.2e (row %d)  maxViolCol=%.2e (col %d)\n",
           maxViolRow, rowIdx, maxViolCol, colIdx);
    pass = 0;
  }

  /* Semantic check: all capacity constraints satisfied */
  double primalTol = Cbc_getDblParam(m, DBL_PARAM_PRIMAL_TOL);
  for (int i = 0; i < mm && pass; i++) {
    double load = 0.0;
    for (int j = 0; j < n; j++) load += inst->w[i * n + j] * sol[j];
    if (load > inst->c[i] + primalTol) {
      printf("    FAIL: capacity violated for dim %d: load=%.2f cap=%d\n",
             i, load, inst->c[i]);
      pass = 0;
    }
  }

  /* Objective check */
  double obj = Cbc_getObjValue(m);
  if (fabs(obj - inst->opt) > 0.5) {
    printf("    FAIL: obj=%.2f expected=%d\n", obj, inst->opt);
    pass = 0;
  }

  if (pass) printf("    PASS obj=%.0f\n", obj);
  Cbc_deleteModel(m);
  return pass;
}

/* ── main ─────────────────────────────────────────────────────────────────── */

int main(void)
{
  printf("=== MDKP Random Instance Tests ===\n");
  int nfail = 0;
  for (int k = 0; k < NUM_MDKP_INSTANCES; k++) {
    if (!test_mdkp(&MDKP_INSTANCES[k])) nfail++;
  }
  if (nfail == 0)
    printf("=== All MDKP tests PASSED ===\n");
  else
    printf("=== %d MDKP test(s) FAILED ===\n", nfail);
  return nfail ? 1 : 0;
}
