/* Maximum (Weighted) Independent Set (MIS/MWIS) tests on generated instances.

   Formulation (maximization):
     maximize   sum_v w[v] * x[v]
     subject to x[u] + x[v] <= 1   for all edges (u,v) in E
                x[v] in {0,1}

   This is the canonical pure binary problem for clique cuts:
     - Independent set in G = clique in complement graph
     - Conflict graph IS the problem structure
     - Tests CglBKClique, CglOddWheel, CglCliqueStrengthening

   For each solve the solution is verified for:
     - structural feasibility via Cbc_checkFeasibility
     - objective value matches known optimum within relative tolerance

   Fixtures in fixtures/*.mps.gz (generated by gen_mis_fixtures.py).
   Includes diverse graph types: random, geometric, grid, tree, planar, etc. */

#include "Cbc_C_Interface.h"
#include "mip_diag.h"
#include "test_utils.h"
#include <math.h>
#include <stdio.h>
#include <string.h>

typedef struct {
  const char *name;
  double expected_obj;
  int max_nodes;
  int timeout_sec;  /* Fallback */
} MisTestCase;

static const MisTestCase mis_test_cases[] = {
  {"mis_n15_sd42_random_uniform", 361.00, 10000, 300},
  {"mis_n20_sd42_geometric_unit", 6.00, 10000, 300},
  {"mis_n16_sd137_grid_diverse", 586.00, 10000, 300},
  {"mis_n18_sd42_k_partite_uniform", 338.00, 10000, 300},
  {"mis_n20_sd137_tree_uniform", 626.00, 10000, 300},
  {"mis_n30_sd42_random_uniform", 490.00, 10000, 300},
  {"mis_n35_sd137_geometric_diverse", 709.00, 10000, 300},
  {"mis_n36_sd42_grid_unit", 18.00, 10000, 300},
  {"mis_n40_sd137_planar_uniform", 1042.00, 10000, 300},
  {"mis_n30_sd42_cycle_uniform", 916.00, 10000, 300},
};

static const int NUM_TESTS = sizeof(mis_test_cases) / sizeof(mis_test_cases[0]);

static int test_mis(const char *fixture_dir, const MisTestCase *tc,
                    MipPerfRecord *perf)
{
  char path[512];
  snprintf(path, sizeof(path), "%s/%s.mps.gz", fixture_dir, tc->name);

  printf("  %s (nodes=%d, expected=%.0f)\n", tc->name, tc->max_nodes, tc->expected_obj);

  perf->name = tc->name; perf->pass = 0; perf->is_optimal = 0;
  perf->nodes = 0; perf->wall_time = 0.0; perf->obj = 1e30;

  Cbc_Model *m = Cbc_newModel();
  Cbc_setLogLevel(m, 0);

  if (Cbc_readMps(m, path) != 0) {
    printf("    FAIL: cannot read %s\n", path);
    Cbc_deleteModel(m);
    return 0;
  }

  Cbc_setMaximumNodes(m, tc->max_nodes);
  double t0 = perf_wall_time();
  Cbc_solve(m);
  perf->wall_time  = perf_wall_time() - t0;
  perf->is_optimal = Cbc_isProvenOptimal(m);
  perf->nodes      = Cbc_getNodeCount(m);

  int pass = 1;
  int nSol = Cbc_numberSavedSolutions(m);

  if (nSol == 0) {
    printf("    FAIL: no feasible solution found (status=%d)\n", Cbc_status(m));
    Cbc_deleteModel(m);
    return 0;
  }

  /* MPS file has negated objective for maximization */
  double obj = -Cbc_getObjValue(m);
  perf->obj = obj;

  /* Check feasibility of best and all pool solutions */
  const double *bestSol = Cbc_getColSolution(m);
  double maxViolRow = 0.0; int rowIdx = -1;
  double maxViolCol = 0.0; int colIdx = -1;

  if (!Cbc_checkFeasibility(m, bestSol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
    printf("    FAIL: best solution infeasible  "
           "maxViolRow=%.2e (row %d)  maxViolCol=%.2e (col %d)\n",
           maxViolRow, rowIdx, maxViolCol, colIdx);
    pass = 0;
  }

  for (int s = 0; s < nSol; s++) {
    const double *sol = Cbc_savedSolution(m, s);
    double solObj = Cbc_savedSolutionObj(m, s);
    maxViolRow = 0.0; rowIdx = -1; maxViolCol = 0.0; colIdx = -1;
    if (!Cbc_checkFeasibility(m, sol, &maxViolRow, &rowIdx, &maxViolCol, &colIdx)) {
      printf("    FAIL: pool solution %d/%d infeasible (obj=%.2f)  "
             "maxViolRow=%.2e (row %d)  maxViolCol=%.2e (col %d)\n",
             s+1, nSol, solObj, maxViolRow, rowIdx, maxViolCol, colIdx);
      pass = 0;
    }
  }

  /* Only validate objective if solver claims optimality */
  if (perf->is_optimal) {
    double rel_err = fabs(obj - tc->expected_obj) / fmax(fabs(tc->expected_obj), 1.0);
    if (rel_err > 1e-3) {
      printf("    FAIL: proven optimal but obj=%.2f expected=%.2f (rel_err=%.2e)\n",
             obj, tc->expected_obj, rel_err);
      pass = 0;
      /* MPS stores negated maximization objective; diag uses raw model values */
      char tmp_sol[512];
      snprintf(tmp_sol, sizeof(tmp_sol), "/tmp/mipster_diag_%s.sol", tc->name);
      mip_diag_write_sol(m, tmp_sol);
      mip_diag_wrong_optimal(build_mps_model, (void *)path, -tc->expected_obj, 300);
      mip_diag_debug_cuts(build_mps_model, (void *)path, -tc->expected_obj, 300,
                          tmp_sol, NULL, NULL);
    }
  }

  if (pass) {
    if (perf->is_optimal)
      printf("    PASS obj=%.0f  nodes=%ld  time=%.3fs  (proven optimal)\n",
             obj, perf->nodes, perf->wall_time);
    else
      printf("    PASS obj=%.0f  nodes=%ld  time=%.3fs  (feasible, not proven optimal)\n",
             obj, perf->nodes, perf->wall_time);
  }

  Cbc_deleteModel(m);
  perf->pass = pass;
  return pass;
}

int main(int argc, char **argv)
{
  if (argc < 2) {
    fprintf(stderr, "Usage: %s <fixture-dir>\n", argv[0]);
    return 1;
  }

  const char *fixture_dir = argv[1];

  printf("=== Maximum Independent Set Tests ===\n");
  int passed = 0, failed = 0;
  MipPerfRecord perf_records[NUM_TESTS];

  for (int i = 0; i < NUM_TESTS; i++) {
    if (test_mis(fixture_dir, &mis_test_cases[i], &perf_records[i]))
      passed++;
    else
      failed++;
  }

  print_perf_summary(perf_records, NUM_TESTS, "Maximum Independent Set");
  printf("\n");
  if (failed == 0)
    printf("=== All %d tests PASSED ===\n", passed);
  else
    printf("=== %d passed, %d FAILED ===\n", passed, failed);

  return (failed == 0) ? 0 : 1;
}

