# Select optimization (-O or -g). -O will be automatically bumped up to the 
# highest level of optimization the compiler supports. If want something in
# between then specify the exact level you want, e.g., -O1 or -O2
OptLevel := -g

##############################################################################
# You should not need to edit below this line unless you are configuring cbc
# for multiple solvers, or for a single solver other than clp.
##############################################################################

# The location of the customized Makefiles
# also inherited from the parent Makefile

include ${MakefileDir}/Makefile.coin
include ${MakefileDir}/Makefile.location

# Include files, library directory and name, compile-time defines.

# The pattern is (hopefully) obvious. Add or uncomment the appropriate lines
# for your favourite solver. The appropriate lines of code must be installed in
# the conditional compilation blocks in CbcMain.cpp in order for any of this to
# work. One conditional compilation block is at the head of the file and
# selects #include headers. The second is at the start of main() and creates a
# vector of available solvers.

IncDir := ${CbcIncDir} ${CglIncDir}
IncDir += ${OsiClpIncDir} ${ClpIncDir}
IncDir += ${OsiIncDir} ${CoinIncDir}
IncDir += ${bzlibIncDir} ${zlibIncDir} $(lapackIncDir)
IncDir := ${ClpIncDir} ${CoinIncDir} ${bzlibIncDir} ${zlibIncDir} $(lapackIncDir)
LibDir := ${ClpLibDir} ${CoinLibDir} ${bzlibLibDir} ${zlibLibDir} $(lapackLibDir) $(GlpkLibDir)
ifeq ($(VolDefine),COIN_HAS_VOL)
LibName := ${ClpLibName} ${CoinLibName} ${bzlibLibName} ${zlibLibName} $(lapackLibName) $(readlineLibName) $(GlpkLibName) $(VolLibName)
else
LibName := ${ClpLibName} ${CoinLibName} ${bzlibLibName} ${zlibLibName} $(lapackLibName) $(readlineLibName)
endif
Define := ${ClpDefine} ${CoinDefine} ${bzlibDefine} ${zlibDefine} $(lapackLibDefine) $(readlineDefine) $(VolDefine)

LibDir += ${CbcLibDir} ${CglLibDir}
LibDir += ${OsiLibDir}

LibName += $(OsiCbcLibName) ${CbcLibName} ${CglLibName} $(OsiClpLibName)
ifeq ($(VolDefine),COIN_HAS_VOL)
LibName += $(VolLibName)
endif
LibName += ${OsiLibName}

Define += ${CbcDefine} ${CglDefine}
Define += ${OsiClpDefine}
Define += ${OsiDefine}
IncDir += ./include ../../Clp/Test

#use clp
CXXFLAGS += $(addprefix -D,COIN_USE_CLP)

#tell parameter handling to allow for CbcModel and OsiSolverInterface
CXXFLAGS += -DCOIN_USE_CBC
##############################################################################
# You should not need to edit below this line.
##############################################################################

CXXFLAGS += $(OPTFLAG)
ifeq ($(OptLevel),-g)
    CXXFLAGS += -DCBC_DEBUG
endif

TESTSRC := CoinSolve.cpp
TESTSRC += CbcOrClpParam.cpp
TESTSRC += unitTestClp.cpp

###############################################################################

space:= $(empty) $(empty)
OptVersion := $(subst $(space),_,$(OptLevel))

TARGETDIR := $(UNAME)$(OptVersion)
DEPDIR := dep

VPATH := . : include : Junk : ${TARGETDIR} : ${DEPDIR} : $(CoinDir)/Clp/Test

#########################################################################

CXXFLAGS += $(addprefix -I,${IncDir})
CXXFLAGS += $(addprefix -D,${Define})

LIBDIRS := ${LibDir}
LIBS    := ${LibName}

LDFLAGS := $(addprefix -L,$(LIBDIRS))
LDFLAGS += $(call ifprefix,$(SHLINKPREFIX),$(LIBDIRS))
LDFLAGS += $(patsubst lib%,-l%,$(basename $(LIBS)))

ifeq ($(findstring Linux,${UNAME}),Linux)
	CXXFLAGS +=	-DREADLINE
endif
#LDFLAGS += -lefence

###############################################################################

TESTOBJ := $(addprefix $(TARGETDIR)/, $(TESTSRC:.cpp=.o))
TESTDEP := $(addprefix $(DEPDIR)/, $(TESTSRC:.cpp=.d))

###############################################################################
# This one must be right before the rules

include ${MakefileDir}/Makefile.rules

###############################################################################

.DELETE_ON_ERROR:

.PHONY: unitTest

unitTest: $(TARGETDIR)/solve

$(TARGETDIR)/solve : $(TESTOBJ)
	@rm -rf Junk
	@echo ""
	@echo Creating solve
	@mkdir -p $(TARGETDIR)
	@rm -f $@
	$(CXX) $(CXXFLAGS) -o $@ $(TESTOBJ) $(LDFLAGS) $(SYSLD) -lm
	${CP} $@ ..

###############################################################################

%::
	@mkdir -p Junk
	touch Junk/$(notdir $@)

###############################################################################

-include $(TESTDEP)
