#!/usr/bin/env python3
"""Generate doc/cbc.1 man page from 'cbc -dumpParameters' JSON output.

Usage:
    python3 doc/generate_manpage.py [path/to/cbc] > doc/cbc.1
"""

import subprocess, sys, os, json, re
from datetime import datetime


def load_params(cbc):
    """Run cbc -dumpParameters and parse the JSON array."""
    out = subprocess.run([cbc, "-dumpParameters"],
                         capture_output=True, text=True, timeout=10).stdout
    # Skip any non-JSON header lines (cbc banner)
    start = out.index("["); end = out.rindex("]") + 1
    return json.loads(out[start:end])


def man_escape(s):
    """Make text safe for groff/troff: replace non-ASCII punctuation with
    ASCII/groff-special equivalents (raw UTF-8 multi-byte sequences trigger
    'invalid input character' warnings under plain -Tascii/-Tutf8 rendering
    without an explicit encoding declaration) and escape literal hyphens so
    they render as ASCII hyphens rather than typographic minus signs."""
    for old, new in [
        ('\u2014', '\\(em'), ('\u2013', '\\(en'),
        ('\u2018', '`'), ('\u2019', "'"), ('\u201c', '"'), ('\u201d', '"'),
        ('\u2208', 'in'), ('\u2192', '->'), ('\u03ba', 'kappa'),
        ('\u2264', '<='), ('\u2265', '>='),
    ]:
        s = s.replace(old, new)
    return s.replace('-', '\\-')


def get_version(cbc):
    out = subprocess.run([cbc, "--version"],
                         capture_output=True, text=True, timeout=10).stdout
    m = re.search(r"CBC\s+(\S+)", out, re.IGNORECASE)
    return m.group(1) if m else "devel"


def group_by_topic(params):
    """Return {topic: [param_dict, ...]} for visible params.

    Parameters without an explicit topic are still shown (grouped under a
    "General" catch-all) as long as they are meant to be visible
    (displayPriority != 0) -- previously such parameters (e.g. rankConflict*,
    rankRange*, extra1-4, help, version, ...) were silently dropped from
    every generated reference.
    """
    topics = {}
    for p in params:
        if p.get("displayPriority", 0) == 0:
            continue
        t = p.get("topic", "") or "General"
        topics.setdefault(t, []).append(p)
    return topics


def humanize_bound(v):
    """Replace sentinel values with human-readable labels."""
    s = str(v)
    if s == "2147483647":
        return "INT_MAX"
    if s == "-2147483647":
        return "\\-INT_MAX"
    if s in ("1e+60", "1e+20"):
        return "infinity"
    if s in ("-1e+60", "-1e+20"):
        return "\\-infinity"
    return s


def emit_param(p, out):
    """Emit one .TP entry: name, short help, and (if applicable) a Values:
    or Range: line giving the allowed keywords/bounds and default -- the
    man page previously showed only the bare name + short help, far less
    detail than the LaTeX/Markdown/HTML references."""
    name = p["name"]
    ptype = p.get("type", "")
    desc = man_escape(p["shortHelp"])
    keywords = p.get("keywords", [])
    dv = p.get("defaultValue", "")

    out.write(f".TP\n.BI \\-{name}\n{desc}\n")

    if keywords:
        kw = ", ".join(man_escape(k) for k in keywords)
        line = f"Values: {kw}"
        if dv != "":
            line += f" (default: {man_escape(str(dv))})"
        out.write(f".br\n{line}\n")
    elif ptype == "integer":
        lo, hi = humanize_bound(p.get("lowerInt", "")), humanize_bound(p.get("upperInt", ""))
        line = f"Range: {lo} to {hi}"
        if dv != "":
            line += f" (default: {dv})"
        out.write(f".br\n{line}\n")
    elif ptype == "double":
        lo, hi = humanize_bound(p.get("lowerDbl", "")), humanize_bound(p.get("upperDbl", ""))
        line = f"Range: {lo} to {hi}"
        if dv != "":
            line += f" (default: {dv})"
        out.write(f".br\n{line}\n")


def emit(version, topics, out):
    date = datetime.now().strftime("%B %Y")
    order = [
        "Stopping",
        "MIP Preprocessing", "MIP Preprocessing \u2014 Bound Propagation", "LP Presolve",
        "Cuts", "Heuristics", "Branching",
        "Tolerances", "Conflict Graph", "Strategy", "Solving",
        "Simplex", "Barrier", "Scaling", "Output", "I/O", "Parallelism",
        "General",
    ]

    out.write(f"""\
.\\" Man page for cbc - auto-generated by doc/generate_manpage.py
.\\" Re-generate: python3 doc/generate_manpage.py path/to/cbc > doc/cbc.1
.TH CBC 1 "{date}" "CBC {version}" "COIN-OR Utilities"
.SH NAME
cbc \\- mixed-integer linear programming solver
.SH SYNOPSIS
.B cbc
.IR model.mps[.gz]
.RI [ options ]
.B \\-solve
.br
.B cbc
.RI [ options ]
.B \\-import
.I file
.B \\-solve
.SH DESCRIPTION
.B cbc
is the COIN-OR Branch and Cut solver, an open-source mixed-integer
programming (MIP) solver.  It reads a model in MPS or LP format,
applies preprocessing, cut generation, and heuristics, then solves
via branch and bound.
.PP
Parameters must appear \\fBbefore\\fR \\fB\\-solve\\fR to take effect.
Both single-dash (\\fB\\-sec\\fR) and double-dash (\\fB\\-\\-sec\\fR) styles
are accepted.
.SH EXAMPLES
.TP
.B cbc model.mps \\-solve
Solve with default settings.
.TP
.B cbc model.mps \\-sec 300 \\-solve
Solve with a 5-minute time limit.
.TP
.B cbc model.mps \\-maxN 10000 \\-ratio 0.01 \\-solve
Stop after 10000 nodes or 1% gap.
.TP
.B cbc model.mps \\-preprocess off \\-solve
Disable integer preprocessing.
.TP
.B cbc model.mps \\-cuts off \\-solve
Disable all cut generators.
.TP
.B cbc model.mps \\-heur off \\-solve
Disable all primal heuristics.
.TP
.B cbc model.mps \\-log 0 \\-solve
Silent mode (no output).
.TP
.B cbc model.mps \\-csvStatistics r.csv \\-solve \\-writeStatistics
Solve and append per-solve statistics to a CSV file.
""")

    for topic in order:
        if topic not in topics:
            continue
        out.write(f".SH {man_escape(topic.upper())}\n")
        for p in topics[topic]:
            emit_param(p, out)

    for topic in topics:
        if topic in order:
            continue
        out.write(f".SH {man_escape(topic.upper())}\n")
        for p in topics[topic]:
            emit_param(p, out)

    out.write("""\
.SH INTERACTIVE MODE
When invoked without arguments or with \\fB\\-\\fR, cbc enters interactive
mode.  Type \\fB?\\fR for a command list, \\fB???\\fR for all commands,
or \\fIparam\\fB??\\fR for detailed help on a specific parameter.
.SH EXIT STATUS
.B cbc
returns 0 on success.
.SH SEE ALSO
.BR clp (1),
.BR glpsol (1)
.PP
Project page: https://github.com/coin-or/Cbc
.SH AUTHORS
COIN-OR Cbc development team.
.br
https://www.coin-or.org/
""")


def main():
    cbc = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/prog/cbc/bin/cbc")
    params = load_params(cbc)
    version = get_version(cbc)
    topics = group_by_topic(params)
    total = sum(len(v) for v in topics.values())
    print(f"Parsed {len(topics)} topics, {total} parameters", file=sys.stderr)
    emit(version, topics, sys.stdout)


if __name__ == "__main__":
    main()
