#!/usr/bin/env python3
"""Generate doc/cbc.1 man page from the cbc binary's --help output.

Usage:
    python3 doc/generate_manpage.py [path/to/cbc] [> doc/cbc.1]

If no binary is given, defaults to ~/prog/cbc/bin/cbc.
The script parses the topic-grouped parameter listing produced by
'cbc --help' and emits a complete troff man page to stdout.
"""

import subprocess
import sys
import re
from datetime import datetime


def get_help_output(cbc_binary):
    """Run cbc --help and return its stdout."""
    result = subprocess.run(
        [cbc_binary, "--help"],
        capture_output=True, text=True, timeout=10
    )
    return result.stdout


def get_version(cbc_binary):
    """Extract version string from cbc --help output."""
    result = subprocess.run(
        [cbc_binary, "--version"],
        capture_output=True, text=True, timeout=10
    )
    for line in result.stdout.splitlines():
        if "CBC" in line or "Cbc" in line:
            # e.g. "CBC devel (git:abc123) — COIN-OR Branch and Cut"
            m = re.search(r"CBC\s+(\S+)", line, re.IGNORECASE)
            if m:
                return m.group(1)
    return "devel"


def parse_topics(help_text):
    """Parse the 'Parameters by topic:' section into {topic: [(name, desc)]}."""
    topics = {}
    current_topic = None
    in_params = False

    for line in help_text.splitlines():
        if line.strip() == "Parameters by topic:":
            in_params = True
            continue
        if not in_params:
            continue

        # Topic header: "  TopicName:"
        m = re.match(r"^  (\S.*):$", line)
        if m:
            current_topic = m.group(1)
            topics[current_topic] = []
            continue

        # Parameter line: "    -paramName   description"
        m = re.match(r"^    -(\S+)\s{2,}(.+)$", line)
        if m and current_topic:
            topics[current_topic].append((m.group(1), m.group(2).strip()))

    return topics


def escape_troff(s):
    """Escape characters special in troff."""
    return s.replace("\\", "\\\\").replace("-", "\\-")


def emit_manpage(version, topics, out):
    """Write the complete man page to out."""
    date = datetime.now().strftime("%B %Y")

    # Preferred topic order
    order = [
        "Stopping", "Cuts", "Heuristics", "Preprocessing", "Branching",
        "Tolerances", "Conflict Graph", "Strategy", "Solving",
        "Simplex", "Barrier", "Scaling",
        "Output", "I/O", "Parallelism",
    ]

    out.write(f'''\
.\\" Man page for cbc - COIN-OR Branch and Cut MIP solver
.\\" Auto-generated by doc/generate_manpage.py — do not edit by hand.
.\\" Re-generate with: python3 doc/generate_manpage.py path/to/cbc > doc/cbc.1
.TH CBC 1 "{date}" "CBC {version}" "COIN-OR Utilities"
.SH NAME
cbc \\- mixed-integer linear programming solver
.SH SYNOPSIS
.B cbc
.IR model.mps[.gz]
.RI [ options ]
.B \\-solve
.br
.B cbc
.RI [ options ]
.B \\-import
.I file
.B \\-solve
.SH DESCRIPTION
.B cbc
is the COIN-OR Branch and Cut solver, an open-source mixed-integer
programming (MIP) solver.  It reads a model in MPS or LP format,
applies preprocessing, cut generation, and heuristics, then solves
via branch and bound.
.PP
Parameters must appear \\fBbefore\\fR \\fB\\-solve\\fR to take effect.
Both single-dash (\\fB\\-sec\\fR) and double-dash (\\fB\\-\\-sec\\fR) styles
are accepted.
.SH EXAMPLES
.TP
.B cbc model.mps \\-solve
Solve with default settings.
.TP
.B cbc model.mps \\-sec 300 \\-solve
Solve with a 5-minute time limit.
.TP
.B cbc model.mps \\-maxN 10000 \\-ratio 0.01 \\-solve
Stop after 10000 nodes or 1% gap.
.TP
.B cbc model.mps \\-preprocess off \\-solve
Disable integer preprocessing.
.TP
.B cbc model.mps \\-cuts off \\-solve
Disable all cut generators.
.TP
.B cbc model.mps \\-heur off \\-solve
Disable all primal heuristics.
.TP
.B cbc model.mps \\-log 0 \\-solve
Silent mode (no output).
.TP
.B cbc model.mps \\-csvStatistics r.csv \\-solve \\-writeStatistics
Solve and append per-solve statistics to a CSV file.
''')

    def write_topic(topic, params):
        section = topic.upper()
        out.write(f".SH {section}\n")
        for name, desc in params:
            # Escape hyphens in description only
            edesc = desc.replace("-", "\\-")
            out.write(f".TP\n.BI \\-{name}\n{edesc}\n")

    # Emit each topic as a section
    for topic in order:
        if topic not in topics:
            continue
        write_topic(topic, topics[topic])

    # Any topics not in the preferred order
    for topic, params in topics.items():
        if topic in order:
            continue
        write_topic(topic, params)

    out.write('''\
.SH INTERACTIVE MODE
When invoked without arguments or with \\fB\\-\\fR, cbc enters interactive
mode.  Type \\fB?\\fR for a command list, \\fB???\\fR for all commands,
or \\fIparam\\fB??\\fR for detailed help on a specific parameter.
.SH EXIT STATUS
.B cbc
returns 0 on success.
.SH SEE ALSO
.BR clp (1),
.BR glpsol (1)
.PP
Project page: https://github.com/coin-or/Cbc
.SH AUTHORS
COIN-OR Cbc development team.
.br
https://www.coin-or.org/
''')


def main():
    import os
    cbc = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/prog/cbc/bin/cbc")

    help_text = get_help_output(cbc)
    version = get_version(cbc)
    topics = parse_topics(help_text)

    if not topics:
        print(f"Error: no topics found in '{cbc} --help' output", file=sys.stderr)
        sys.exit(1)

    total = sum(len(v) for v in topics.values())
    print(f"Parsed {len(topics)} topics, {total} parameters", file=sys.stderr)

    emit_manpage(version, topics, sys.stdout)


if __name__ == "__main__":
    main()
