#!/usr/bin/env python3
"""Generate doc/mipster.1 man page from 'mipster -dumpParameters' JSON output.

Usage:
    python3 doc/generate_manpage.py [path/to/mipster] > doc/mipster.1
"""

import subprocess, sys, os, json, re
from datetime import datetime


def load_params(cbc):
    """Run mipster -dumpParameters and parse the JSON array."""
    out = subprocess.run([cbc, "-dumpParameters"],
                         capture_output=True, text=True, timeout=10).stdout
    # Skip any non-JSON header lines (banner)
    start = out.index("["); end = out.rindex("]") + 1
    return json.loads(out[start:end])


def get_version(cbc):
    out = subprocess.run([cbc, "--version"],
                         capture_output=True, text=True, timeout=10).stdout
    m = re.search(r"(?:MIPster|CBC)\s+(\S+)", out, re.IGNORECASE)
    return m.group(1) if m else "devel"


def group_by_topic(params):
    """Return {topic: [param_dict, ...]} for visible params with a topic."""
    topics = {}
    for p in params:
        t = p.get("topic", "")
        if not t or p.get("displayPriority", 0) == 0:
            continue
        topics.setdefault(t, []).append(p)
    return topics


def emit(version, topics, out):
    date = datetime.now().strftime("%B %Y")
    order = [
        "Stopping", "Cuts", "Heuristics", "Preprocessing", "Branching",
        "Tolerances", "Conflict Graph", "Strategy", "Solving",
        "Simplex", "Barrier", "Scaling", "Output", "I/O", "Parallelism",
    ]

    out.write(f"""\
.\\" Man page for mipster — auto-generated by doc/generate_manpage.py
.\\" Re-generate: python3 doc/generate_manpage.py path/to/mipster > doc/mipster.1
.TH MIPSTER 1 "{date}" "MIPster {version}" "MIPster"
.SH NAME
mipster \\- mixed-integer linear programming solver
.SH SYNOPSIS
.B mipster
.IR model.mps[.gz]
.RI [ options ]
.B \\-solve
.br
.B mipster
.RI [ options ]
.B \\-import
.I file
.B \\-solve
.SH DESCRIPTION
.B mipster
is an open-source mixed-integer programming (MIP) solver based on the
COIN-OR Branch and Cut engine.  It reads a model in MPS or LP format,
applies preprocessing, cut generation, and heuristics, then solves
via branch and bound.
.PP
Parameters must appear \\fBbefore\\fR \\fB\\-solve\\fR to take effect.
Both single-dash (\\fB\\-sec\\fR) and double-dash (\\fB\\-\\-sec\\fR) styles
are accepted.
.SH EXAMPLES
.TP
.B mipster model.mps \\-solve
Solve with default settings.
.TP
.B mipster model.mps \\-sec 300 \\-solve
Solve with a 5-minute time limit.
.TP
.B mipster model.mps \\-maxN 10000 \\-ratio 0.01 \\-solve
Stop after 10000 nodes or 1% gap.
.TP
.B mipster model.mps \\-preprocess off \\-solve
Disable integer preprocessing.
.TP
.B mipster model.mps \\-cuts off \\-solve
Disable all cut generators.
.TP
.B mipster model.mps \\-heur off \\-solve
Disable all primal heuristics.
.TP
.B mipster model.mps \\-log 0 \\-solve
Silent mode (no output).
.TP
.B mipster model.mps \\-csvStatistics r.csv \\-solve \\-writeStatistics
Solve and append per-solve statistics to a CSV file.
""")

    for topic in order:
        if topic not in topics:
            continue
        out.write(f".SH {topic.upper()}\n")
        for p in topics[topic]:
            desc = p["shortHelp"].replace("-", "\\-")
            out.write(f".TP\n.BI \\-{p['name']}\n{desc}\n")

    for topic in topics:
        if topic in order:
            continue
        out.write(f".SH {topic.upper()}\n")
        for p in topics[topic]:
            desc = p["shortHelp"].replace("-", "\\-")
            out.write(f".TP\n.BI \\-{p['name']}\n{desc}\n")

    out.write("""\
.SH INTERACTIVE MODE
When invoked without arguments or with \\fB\\-\\fR, mipster enters interactive
mode.  Type \\fB?\\fR for a command list, \\fB???\\fR for all commands,
or \\fIparam\\fB??\\fR for detailed help on a specific parameter.
.SH EXIT STATUS
.B mipster
returns 0 on success.
.SH SEE ALSO
.BR clp (1)
.PP
Project page: https://github.com/h-g-s/mipster
.SH AUTHORS
MIPster development team.
.br
https://github.com/h-g-s/mipster
""")


def main():
    cbc = sys.argv[1] if len(sys.argv) > 1 else os.path.expanduser("~/prog/cbc/bin/mipster")
    params = load_params(cbc)
    version = get_version(cbc)
    topics = group_by_topic(params)
    total = sum(len(v) for v in topics.values())
    print(f"Parsed {len(topics)} topics, {total} parameters", file=sys.stderr)
    emit(version, topics, sys.stdout)


if __name__ == "__main__":
    main()
