/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class com_epri_omi_Block */

#ifndef _Included_com_epri_omi_Block
#define _Included_com_epri_omi_Block
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: VERBOSE */
/* Inaccessible static: zeroTol */
#undef com_epri_omi_Block_DENSE
#define com_epri_omi_Block_DENSE 0L
#undef com_epri_omi_Block_ROW_ORDER
#define com_epri_omi_Block_ROW_ORDER 1L
#undef com_epri_omi_Block_COLUMN_ORDER
#define com_epri_omi_Block_COLUMN_ORDER 2L
#undef com_epri_omi_Block_TRIPLES
#define com_epri_omi_Block_TRIPLES 3L
#undef com_epri_omi_Block_UNKNOWN
#define com_epri_omi_Block_UNKNOWN 4L
/* Inaccessible static: blockTypes */
/*
 * Class:     com_epri_omi_Block
 * Method:    pprint
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_epri_omi_Block_pprint
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
