/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class com_epri_omi_Model */

#ifndef _Included_com_epri_omi_Model
#define _Included_com_epri_omi_Model
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: VERBOSE */
/* Inaccessible static: CHECK_DOMAIN */
/* Inaccessible static: SLIGHTLY_POSITIVE */
/* Inaccessible static: SLIGHTLY_NEGATIVE */
/* Inaccessible static: class_00024com_00024epri_00024omi_00024Parameter */
/* Inaccessible static: class_00024com_00024epri_00024omi_00024CompoundSet */
/* Inaccessible static: array_00024Z */
/* Inaccessible static: class_00024com_00024epri_00024omi_00024Model */
/*
 * Class:     com_epri_omi_Model
 * Method:    pprint
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_epri_omi_Model_pprint
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_epri_omi_Model
 * Method:    pManne
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_epri_omi_Model_pManne
  (JNIEnv *, jobject);

/*
 * Class:     com_epri_omi_Model
 * Method:    pMPS
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_epri_omi_Model_pMPS
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_epri_omi_Model
 * Method:    psetup
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_epri_omi_Model_psetup
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_epri_omi_Model
 * Method:    psolve
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_epri_omi_Model_psolve
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_epri_omi_Model
 * Method:    pwriteMPS
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_epri_omi_Model_pwriteMPS
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_epri_omi_Model
 * Method:    pestimate
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_epri_omi_Model_pestimate
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_epri_omi_Model
 * Method:    poption
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_epri_omi_Model_poption
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_epri_omi_Model
 * Method:    poptioni
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_epri_omi_Model_poptioni
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_epri_omi_Model
 * Method:    poptiond
 * Signature: (Ljava/lang/String;D)I
 */
JNIEXPORT jint JNICALL Java_com_epri_omi_Model_poptiond
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     com_epri_omi_Model
 * Method:    ngetObjective
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_epri_omi_Model_ngetObjective
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
