/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class com_epri_omi_Base */

#ifndef _Included_com_epri_omi_Base
#define _Included_com_epri_omi_Base
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_epri_omi_Base
 * Method:    pprint
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_epri_omi_Base_pprint
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
