// CbcLpParamScorer.hpp — LP parameter recommendation for MIPster
//
// Auto-generated by lp_tune_scripts/build_lp_param_scorer.py
// DO NOT EDIT MANUALLY — re-run the script to regenerate.
//
// Model: RandomForest classifier (n_estimators=150, max_depth=8)
// Training data: 380 instances x 207 OsiFeatures
// Classes (23): cbc_default, dual_default, dual_pertv50, dual_pertv52, dual_pertv61, dual_pesteep, …
#pragma once

/// Returns the recommended LP parameter tag for the given feature vector.
/// @param features  Array of OsiFeatures::OFCount doubles (see OsiFeatures.hpp).
/// @return  A const C string with the recommended parameter tag, e.g.
///          "dual_pesteep_psineg1".  The pointer is valid for the lifetime
///          of the program (points into a static table).
const char *cbcRecommendLpParam(const double *features);
